### ISSUE TITLE
prometheus :bosh dns report handlers.upcheckhandler  Request [0] [upcheck.bosh-dns]

### ISSUE THREAD

**Issue by leolzbing521** [bosh-prometheus/prometheus-boshrelease#156]
bosh dns report handlers.upcheckhandler  Request [0] [upcheck.bosh-dns] 0 200000ns
DEBUG - stata /var/vcap/instance/dns/records.json

**Comment by frodenas** [comment]
Hey @leolzbing521, I don't understand if you're reporting a bug, or you're trying to ask something, or how bosh dns is involved in this release. Can you please add more details?

**Comment by frodenas** [comment]
Closing this, please reopen with more details if you are still facing an issue.
