### ISSUE TITLE
Concourse Overview InfluxDB Dashboards use Prometheus Datasource

### ISSUE THREAD

**Issue by scnewma** [bosh-prometheus/prometheus-boshrelease#162]
The dashboards provided in `jobs/concourse_influxdb_dashboards/templates/concourse_overview.json` use Prometheus as the datasource for extracting the template.

I not super familiar with these Grafana dashboards, but in my deployment they do not work.  If I manually update the templating section to define `$bosh_deployment` to use `influxdb` as the datasource with `show tag values with key = "bosh-deployment"` as the query it seems to work.

Is this the correct way to use this?  Was the `concourse-overview.json` dashboard for influx designed to import prometheus data as well?

**Comment by frodenas** [comment]
Yes, the `concourse_overview.jsob`dashboard use data from 2 datasources, and it requires the [node_exporter](https://github.com/bosh-prometheus/node-exporter-boshrelease) running at the concourse VM.

Some details at the [monitor-concourse-influxdb.yml](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/manifests/operators/monitor-concourse-influxdb.yml) ops-file or at the README:

*Enables monitoring Concourse CI < v3.8.0. Requires node exporter on Concourse VMs (probably as a BOSH add-on) and InfluxDB to be deployed independently and configured as a data source in Grafana as well as Concourse configured to send events to InfluxDB*

**Comment by scnewma** [comment]
Thank you for your guidance.  

I had the node_exporter installed.  It turned out that my issue was with prometheus not actually scraping my concourse nodes as expected.
