### ISSUE TITLE
Netcat option "-z" not implemented with RedHat/CentOS distributions

### ISSUE THREAD

**Issue by osaluden** [bosh-prometheus/prometheus-boshrelease#163]
Grafana admin password shell script uses "nc -z" command to test Grafana TCP port availability (jobs/grafana/templates/bin/grafana-admin-password).

I propose to replace (line 8) :
```shell
if nc -z 127.0.0.1 <%= p('grafana.server.http_port') %>; then
```
by
```shell
if nc 127.0.0.1 <%= p('grafana.server.http_port') %> < /dev/null; then
```
This command works on both Ubuntu and CentOS stemcells.

**Comment by frodenas** [comment]
sounds good, can you please submit a PR?

**Comment by osaluden** [comment]
Thank you for your feedback. PR submitted: https://github.com/bosh-prometheus/prometheus-boshrelease/pull/171

**Comment by frodenas** [comment]
Merged.
