### ISSUE TITLE
Add additional BOSH director for monitoring

### ISSUE THREAD

**Issue by prashantgnet** [bosh-prometheus/prometheus-boshrelease#166]
Hello,

Not exactly issue!

I have setup prometheus-boshrelease on bosh director "A" which has CF environment and grafana gives me very nice results. Now, I really like to add bosh director "B" which has solution specific services and I would like to view monitoring of instances under bosh director "B" using bosh director "A"'s interface, it is possible? or do I need to setup separate environment under bosh director "B"

Thanks,
Prashant

**Comment by benjaminguttmann-avtq** [comment]
Hey, 

I hope I got the question right. It is possible, if you add another bosh exporter that is gathering the data of your bosh director 'B' and configure your prometheus scrape config to scrape the second bosh exporter as well. The alerts will be automatically applied to your second director as well. In the Grafana you are then able to choose between both directors. 

Please be aware that it is not possible to have two bosh exporters on 1 VM so you need another VM to put the bosh exporter onto. In our case we are using several bosh/firehose/cf exporters all in one prometheus. 

I hope this will help you. If you got further question I can explain it in more detail.

BR,

Benjamin

**Comment by prashantgnet** [comment]
Thanks a lot Benjamin for great explanation. I am closing this.
