### ISSUE TITLE
No data in Doppler / Metron Dashboards

### ISSUE THREAD

**Issue by benjaminguttmann-avtq** [bosh-prometheus/prometheus-boshrelease#170]
Hey, 

since a update last week we do not see any metrics inside the 'CF: Doppler Server' and 'CF: Metron Agent: Doppler' Dashboards. I am wondering if this might be related to the changes in the Loggregator Release (https://github.com/cloudfoundry/loggregator-release/releases/tag/v101.5). We are currently using Prometheus v21.1.0.

Regards,
Benjamin

**Comment by frodenas** [comment]
Check at the promethus console if there is any `*doppler_server*` metric please? If not, this might mean that loggregator has changed metric names or that they're not exposing those metrics anymore.

**Comment by benjaminguttmann-avtq** [comment]
Maybe this is related to the topic:

https://github.com/cloudfoundry/loggregator-release/releases/tag/v101.4

**Comment by benjaminguttmann-avtq** [comment]
@frodenas : Any other suggestions on how to further check the issue by myself?

**Comment by frodenas** [comment]
@benjaminguttmann-avtq If `loggregator` has renamed some metrics, we will need to figure out what are the new metric names. In order to do so, I usually go to the prometheus console and look for metric names (ie, the ones starting from `firehose_*`). Another option is just to hit the `firehose_exporter` metrics endpoint to get a list of all exporter metric  (`http://<firehose exporter ip address>:9186/metrics`).

Once we have a list of renamed metrics, then we will need to modify the dashboards to support both metric names. This can be done using an `or` clause, prometheus will look for the first metric name and if it doesn't exist, then it will look for the second metric name.

**Comment by benjaminguttmann-avtq** [comment]
@frodenas : Thanks I will check the values and try to adapt the dashboard as good as possible.

**Comment by benjaminguttmann-avtq** [comment]
@frodenas : I was able to check most of the metrics this morning. 

It seems like it would be a better attempt to create new dashboards and name them something like: `CF Doppler Server v2` because the metrics used for the templating are no longer available and using 'OR' in there is not possible. 

Also nearly all `dropsonde` metrics are gone. 
I replaced the old metrics with the new, where possible, and tried to enter some new panels to the dashboards based on [Loggegrator Release Metrics Descriptions](https://github.com/cloudfoundry/loggregator-release/blob/develop/docs/metric_descriptions.md).

I attached screenshots for a `CF: Doppler Server v2 dashboard` and a `CF: Metron Agent v2 dashboard`. 

If you already got some things I could adjust just tell me otherwise I will create a PR after I finished the details (like descriptions and so on)

<img width="1427" alt="bildschirmfoto 2018-03-14 um 08 53 44" src="https://user-images.githubusercontent.com/13198546/37389879-461facf8-2766-11e8-99b7-714d8ee75007.png">
<img width="1434" alt="bildschirmfoto 2018-03-14 um 08 52 25" src="https://user-images.githubusercontent.com/13198546/37389880-463e8470-2766-11e8-9d68-1a51d6c391a6.png">

**Comment by frodenas** [comment]
I have not looked into this, so go ahead and please submit a PR as soon as it's ready. thanks!

**Comment by making** [comment]
Updating to [PAS 2.1](https://docs.pivotal.io/pivotalcf/2-1/pcf-release-notes/runtime-rn.html#2.1.0) gets same issue as it uses loggregator 101.5

**Comment by xyloman** [comment]
@making +1 just finished an upgrade to our sandbox PAS environment and experienced the same thing.  Was just checking on this after seeing this issue a few weeks back and wondered if we would experience this after the upgrade.

**Comment by xyloman** [comment]
Actually I stand corrected, we see data in CF: Metron Agent and CF: Metron Agent Doppler, however, we do not see data in CF: Doppler Server but looking back historically we haven't had data in that dashboard since upgrading to 2.0 of PAS.

**Comment by frodenas** [comment]
Solved at #182
