### ISSUE TITLE
Job 'prometheus2' not found in Template table

### ISSUE THREAD

**Issue by jyriok** [bosh-prometheus/prometheus-boshrelease#184]
Hello, 

recently my pipeline for prometheus doesn't work anymore with this error message :

> Task 2307 | 10:08:26 | Preparing deployment: Preparing deployment (00:00:00)
>                      L Error: Job 'prometheus2' not found in Template table
> Task 2307 | 10:08:26 | Error: Job 'prometheus2' not found in Template table

i've see on master branch the job "prometheus" has been change to "prometheus2" recently 

Master branch can be used on prod ?

**Comment by jyriok** [comment]
for info,  on my pipeline i use this opsfile :
```
      manifest: prometheus/manifests/prometheus.yml
      ops_files:
      - prometheus/manifests/operators/monitor-bosh.yml
      - prometheus/manifests/operators/monitor-cf.yml
      - prometheus/manifests/operators/enable-cf-route-registrar.yml
```

**Comment by frodenas** [comment]
No, you should always use a release branch: `git checkout v...` (replace v... with one the of versions at https://github.com/bosh-prometheus/prometheus-boshrelease/releases).

**Comment by jyriok** [comment]
thanks for you answer.

when you say "release branch" you mean "tag" ? 

i use git-resource for my concourse and it don't seem we can target to a specific "tag", only "branch". but maybe i misunderstood , i will search a little more far :)

**Comment by frodenas** [comment]
You can use the concourse [github-release](https://github.com/concourse/github-release-resource) resource, besides being triggered when a new release is released, it has the ability to download the source code (tarball or zip compressed), so you will also get the manifest and op files.

**Comment by jyriok** [comment]
great ! i'll try that ! thanks ;)
