### ISSUE TITLE
postgres fails to restart after VM reboot

### ISSUE THREAD

**Issue by kukgini** [bosh-prometheus/prometheus-boshrelease#185]
Because of this: https://github.com/cloudfoundry/postgres-release/issues/33
Postgres is better upgrade to V24

**Comment by frodenas** [comment]
Next version of the manifests bumps the postgres release to v28. See the manifest [here](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/manifests/prometheus.yml#L180).

If you don't want to wait until a new release is created, you can bump it manually by updating the [prometheus.yml](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/manifests/prometheus.yml) with a newer postgres release version.

**Comment by kukgini** [comment]
Oh. I should have checked master branch before. Anyway, thank you.
