### ISSUE TITLE
alerts/templates files format .yml

### ISSUE THREAD

**Issue by Alexvianet** [bosh-prometheus/prometheus-boshrelease#186]
Why in source code we have /var/vcap/jobs/bosh_alerts/bosh_jobs.alerts.yml 
and in already created bosh release we get /var/vcap/jobs/bosh_alerts/bosh_jobs.alerts

![screenshot from 2018-04-12 10-08-42](https://user-images.githubusercontent.com/17483589/38661580-060a8c10-3e3a-11e8-83c8-7fc7a58a0fda.png)

**Comment by frodenas** [comment]
Bacause you're looking at the [v21.1.1](https://github.com/bosh-prometheus/prometheus-boshrelease/tree/v21.1.1) release, and when we created that release, we had not renamed the files yet.

Just the the source code using that release tag, for example the [bosh_alerts](https://github.com/bosh-prometheus/prometheus-boshrelease/tree/v21.1.1/jobs/bosh_alerts/templates) directory, and you'll see it was still using the old format.
