### ISSUE TITLE
Can I deploy prometheus on one director to monitor PCF on another?

### ISSUE THREAD

**Issue by fgraichen** [bosh-prometheus/prometheus-boshrelease#187]
I am trying to deploy Prometheus on on Bosh Director  but pull data from our PCF foundations.

/opt/pcf/bin/bosh2 -e cc-sand -d prometheus deploy manifests/prometheus.yml --vars-store prometheus-sand-parms.txt -o manifests/operators/monitor-bosh.yml --var-file bosh_ca_cert=pcfsand.cert -o manifests/operators/monitor-cf.yml -o manifests/operators/enable-grafana-uaa.yml  -o manifests/operators/enable-cf-route-registrar.yml  -v traffic_controller_external_port=9186 -v skip_ssl_verify=true --var-file uaa_ssl.ca=pcfsand.cert --var-file uaa_ssl.certificate=uaa.key  --var-file uaa_ssl.private_key=uaa_rsa.key

This is what I put in the vars file…

This is the info for the PCF foundation ---  
bosh_ca_cert: pcfsand.cert
bosh_password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
bosh_url: 10.164.127.4
bosh_username: director
cf_deployment_name: cf-5cc834eddd3c4e259966 
metron_deployment_name: cf-5cc834eddd3c4e259966
opsman_url: ycdcpcfomsand.duke-energy.com
pcf_opsman_admin_password: xxxxxxxx
pcf_opsman_admin_username: pcfadminsand
uaa_bosh_exporter_client_secret: xxxxxxxxxx
uaa_clients_cf_exporter_secret: xxxxxxx
uaa_clients_firehose_exporter_secret: xxxxxxxxx

This is cloud-config info for the non PCF bosh director
deploy_azs:
- AZ1
deployment_network: CDC_PCF_Dev_Concourse_v1225
deploy_vm_type_micro: micro
deploy_vm_type_small: small

github_token: xxxxxxxxxxxxxxxxxxxxxxxx alertmanager_mesh_password: xxxxxxxxxxxxxxxxxxxxxxxx
alertmanager_password: xxxxxxxxxxxxxxxxxxxxxx
alertmanager_smtp_auth_password: xxxxxxxxxxxxxxxxxx
alertmanager_smtp_auth_username: cftst
alertmanager_smtp_from: fgraich@duke-energy.com
alertmanager_smtp_require_tls: true
alertmanager_smtp_smarthost: authenticatedsmtp.duke-energy.com:25
grafana_password: xxxxxxxxxxx
grafana_secret_key: xxxxxxxxxxxxxxx
grafana_smtp_enabled: true
grafana_smtp_host: authenticatedsmtp.duke-energy.com:25
metrics_environment: pcfsand2
prometheus_password: xxxxxxxxxxxxxxxx
skip_ssl_verify: true
system_domain: system.sand-pcf.duke-energy.com

This is based on these insructions…     

If you want to monitor your Cloud Foundry platform, first update your cf-deployment adding the add-prometheus-uaa-clients.yml op file. This will add the UAA clients required to gather information from the Cloud Foundry API and Firehose.

Then add the monitor-cf.yml op file by running the following command (filling the required variables with your own values):

bosh -d prometheus deploy manifests/prometheus.yml \
  --vars-store tmp/deployment-vars.yml \
  -o manifests/operators/monitor-bosh.yml \
  -v bosh_url= \
  -v bosh_username= \
  -v bosh_password= \
  --var-file bosh_ca_cert= \
  -v metrics_environment= \
  -o manifests/operators/monitor-cf.yml \
  -v metron_deployment_name= \
  -v system_domain= \
  -v uaa_clients_cf_exporter_secret= \
  -v uaa_clients_firehose_exporter_secret= \
  -v traffic_controller_external_port= \
  -v skip_ssl_verify=
When I go to execute the deployment:

Task 1156

21:09:29 | Preparing deployment: Preparing deployment (00:00:00)
            L Error: Unable to process links for deployment. Errors are:
  - Can't find deployment cf-5cc834eddd3c4e259966

21:09:29 | Error: Unable to process links for deployment. Errors are:
  - Can't find deployment cf-5cc834eddd3c4e259966

If I list the deployments for the PCF foundation:

$ /opt/pcf/bin/bosh2 -e  pcf-sandbox login
Email (): director
Password ():

Successfully authenticated with UAA

Succeeded
$ /opt/pcf/bin/bosh2 -e  pcf-sandbox deployments
Using environment '10.164.63.194' as user 'director' (bosh.*.read, openid, bosh.*.admin, bosh.read, bosh.admin)

Name                                                   Release(s)                                  Stemcell(s)                                       Team(s)                             Cloud Config
cf-5cc834eddd3c4e259966                                backup-and-restore-sdk/1.2.1                bosh-vsphere-esxi-ubuntu-trusty-go_agent/3468.21  -                                   latest
                                                       binary-offline-buildpack/1.0.15
                                                       bosh-dns/0.1.0
                                                       bosh-dns-aliases/0.0.1
                                                       bosh-system-metrics-forwarder/0.0.11
                                                       capi/1.44.20

Which leads me to believe that when it is looking for the deployment it is not logged into the PCF director.  

Am I just not understanding the directions?  Is what I am trying to do possible (Bosh A running Prometheus while Bosh B is the PCF bosh deployment)?

**Comment by frodenas** [comment]
The manifest files included in this repo are intended to be used when deployments are in the same director. As your `prometheus` deployment is running on a different director than the `cf` deployment, the BOSH links do NOT work.

You will need to create your own manifest file to support your topology (and I'm assuming there's no traffic restriction from the `prometheus` to the `cf` deployment networks). You can do this by updating the [enable-cf-route-registrar.yml](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/manifests/operators/enable-cf-route-registrar.yml) and overriding the [nats link](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/manifests/operators/enable-cf-route-registrar.yml#L26) to use [manual linking](http://bosh.io/docs/links-manual.html):

```yaml
consumes:
  nats:
    instances:
      - address: <Your CF NATS IP Address 1>
      - address: <Your CF NATS IP Address 2>
    properties:
      port: <Your CF NATS port>
      user: <Your CF NATS user>
      password: <Your CF NATS password>
```

Alternativelly, you can use plain properties instead of BOSH links by removing the whole `consumes` section and adding the required properties:

```yaml
name: route_registrar
release: routing
properties:
  nats:
    machines:
      - <Your CF NATS IP Address 1>
      - <Your CF NATS IP Address 2>
    port: <Your CF NATS port>
    user: <Your CF NATS user>
    password:  <Your CF NATS password>  
  route_registrar:
  ...
```

**Comment by frodenas** [comment]
Closing this issue as this topology needs manual manifest files.
