### ISSUE TITLE
Broken links in alert emails

### ISSUE THREAD

**Issue by bruxelles86** [bosh-prometheus/prometheus-boshrelease#192]
Hi there

We're getting broken links in our alerts (as far as we can tell, all of them). For example, this alert...

![screen shot 2018-04-23 at 12 23 04](https://user-images.githubusercontent.com/20523607/39123927-719c5840-46f1-11e8-84e3-9f827ba957d5.png)

...has a link to `http://ff0ac796-fbf3-414c-ad47-25927d0a821d:9093/#/alerts?receiver=default`, which points nowhere (`ff0ac796-fbf3-414c-ad47-25927d0a821d’s server IP address could not be found.`)

It seems that the way these links are built isn't something we have any control over in the manifest. Any ideas?

Thanks!

**Comment by mkuratczyk** [comment]
You need to set the `external_url` property when deploying: https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/jobs/alertmanager/spec#L37

**Comment by frodenas** [comment]
What @mkuratczyk said. If you don't specify the `external_url` property, alertmanager will use the [hostname](https://github.com/prometheus/alertmanager/blob/master/cmd/alertmanager/main.go#L414).

**Comment by bruxelles86** [comment]
Aha thanks guys! I'll give that a try
