### ISSUE TITLE
How to make bosh_exporter use uaa client id and secret instead of user id and password

### ISSUE THREAD

**Issue by fgraichen** [bosh-prometheus/prometheus-boshrelease#195]
bosh_exporter --bosh.url=xxxxxxx --bosh.username=director --bosh.password=xxxxxxxx --bosh.ca-cert-file=/var/vcap/jobs/bosh_exporter/config/bosh_ca_cert.pem --metrics.environment=pcfawsdev --sd.filename=/var/vcap/store/bosh_exporter/bosh_target_groups.json --web.listen-address=:9190

I tested this by running it with the bosh client id and secret by running this command on the vm with these values and it works.  I just cant figure out how to get this command overridden.

I have tried multiple permutations of the variable file, I tried to change the monitor-bosh.yml but I assume there is likely an easier way that I am not seeing.

If I run with UID and Password the refresh token expires and I stop getting data.

Thanks
Fred

**Comment by frodenas** [comment]
You need to use the [enable-bosh-uaa.yml](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/manifests/operators/enable-bosh-uaa.yml) op-file or a fork of it if using a different `client-id`. See [Using BOSH Service Discovery](https://github.com/bosh-prometheus/prometheus-boshrelease#using-bosh-service-discovery) at the README for more details.
