### ISSUE TITLE
rule_files are not loading

### ISSUE THREAD

**Issue by sattan66** [bosh-prometheus/prometheus-boshrelease#205]
Hi, 

The rule_files are not loading when the Prometheus config files is configured as 

rule_files: ["/var/vcap/jobs/bosh_alerts/*.alerts","/var/vcap/jobs/cloudfoundry_alerts/*.alerts"," ......

so I did an manual edit to /var/vcap/jobs/prometheus2/config/prometheus.yml as below (by providing the extension **.yml** to every alert rule file) is fixing the issue.

rule_files: ["/var/vcap/jobs/bosh_alerts/*.alerts**.yml**","/var/vcap/jobs/cloudfoundry_alerts/*.alerts**.yml**","....

kindly help me in having a permanent fix for this issue. 

Thanks,

**Comment by frodenas** [comment]
What op-files are you using? The default ones are already setting the `*.alerts.yml` extension (see the [monitor-bosh.yml](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/manifests/operators/monitor-bosh.yml#L22) example).

**Comment by benjaminguttmann-avtq** [comment]
@sattan66 : Are you sure that the alert configuration itself is correct, that means did you 'translate' your alert configuration from the prometheus style to yml?
You can check your alert definition with the promtool which can be found under `/var/vcap/packages/prometheus/bin/promtool`. To validate the rule file you should use the tool with the following command `promtool check-rules <files>`.

**Comment by sattan66** [comment]
I am closing this issue, as the mistake was from my side at the deployment manifest. Now i fixed it.
