### ISSUE TITLE
path_prefix is not aligned correctly in the prometheus.yml

### ISSUE THREAD

**Issue by sattan66** [bosh-prometheus/prometheus-boshrelease#206]
Hi,

The path_prefix is not aligned correctly in the prometheus.yml , which in turn affects the start of prometheus2 and also not assigning the prefix to the alertmanager URL. 

/var/vcap/jobs/prometheus2/config/prometheus.yml

![image](https://user-images.githubusercontent.com/26006689/40654068-7e7ec774-633d-11e8-8d30-e34aef55d7e3.png)

logs:
/var/vcap/sys/log/prometheus2/prometheus.stderr.log

level=info ts=2018-05-29T08:30:34.643305005Z caller=main.go:573 msg="Notifier manager stopped"
level=error ts=2018-05-29T08:30:34.643387763Z caller=main.go:582 err="Error loading config couldn't load configuration (--config.file=/var/vcap/jobs/prometheus2/config/prometheus.yml): parsing YAML file /var/vcap/jobs/prometheus2/config/prometheus.yml: yaml: line 31: did not find expected key"
level=info ts=2018-05-29T08:30:34.643417443Z caller=main.go:584 msg="See you next time!"

so to make it run correctly , i have adjusted the prometheus.yml file manually  at the alerting section as below

![image](https://user-images.githubusercontent.com/26006689/40654182-d5741fc0-633d-11e8-9e4c-c27bdfc0d5fd.png)

Kindly let me know , if this is a bug, or there is some configuration change needed at the deployment manifest.

Thanks,
Sattanathan.S

**Comment by benjaminguttmann-avtq** [comment]
Hi,

I got a question.
Could you please check if it is still working if you just change the order of properties.

That means 

```
 alertmanagers: 
   path_prefix:  <prefix> 
   - static_configs: 
     - targets: [] 

 alertmanagers: 
   - static_configs: 
     - targets: [] 
     path_prefix:  <prefix> 
```

And check if this still working?
I think this would make a fix easier in the job.

Thanks,

Benjamin

**Comment by sattan66** [comment]
Hi Benjamin,

yes, it works when the config is changed as below as well. 

![image](https://user-images.githubusercontent.com/26006689/40656250-258f7f1c-6344-11e8-86d5-cb87c14f17de.png)

Thanks,
Sattanathan.S
