### ISSUE TITLE
no prometheus_notifications_* metrics after migration to prometheus2

### ISSUE THREAD

**Issue by Alexvianet** [bosh-prometheus/prometheus-boshrelease#209]
Аfter migration to prometheus2
haven't any prometheus_notifications_* metrics
did someone have the same issue, and how to fix that if we can.
![image pasted at 2018-5-31 01-48](https://user-images.githubusercontent.com/17483589/40797995-9ab6d63a-6512-11e8-92e5-a2dc7a1f1cd1.png)

**Comment by benjaminguttmann-avtq** [comment]
Hi,

I checked our environments and could not confirm the behaviour your are describing :-/ What happens if you curl the prometheus metrics endpoint? Perhaps you will receive an error message there ?
