### ISSUE TITLE
App:latency  dashboard latency  What does the client and server mean

### ISSUE THREAD

**Issue by leolzbing521** [bosh-prometheus/prometheus-boshrelease#213]
What does the client and server mean,I think it works like this:
|Client| ---|clientDuration ------|GoRouter|---serverDuration ---|Diego Cell|
![790506529](https://user-images.githubusercontent.com/5356341/41214994-b3c45104-6d80-11e8-83d5-c869b7e12dd2.jpg)

**Comment by leolzbing521** [comment]
and why server time > client time

**Comment by benjaminguttmann-avtq** [comment]
Closed due to inactivity; Please feel free to re-open if issue still persists
