### ISSUE TITLE
Some series labels are lost with current alerts definitions

### ISSUE THREAD

**Issue by aveyrenc** [bosh-prometheus/prometheus-boshrelease#215]
On some alerts, we lose most of the labels that were attached to the original series that were evaluated. This can be problematic, because these labels can be used to do some advanced routing in Alertmanager or even help troubleshooting.

This is due to the fact that most alerts use aggregation functions and in Prometheus they return a vector of the [aggregated labels only](https://prometheus.io/docs/prometheus/latest/querying/operators/#aggregation-operators).

For example, the `ProbeUnsuccessful` alert aggregates on `instance`, so every other label is lost:
```
min(probe_success) by(instance) != 1
```

One way we could solve this is to use PromQL's join feature. This is how we could rewrite the `ProbeUnsuccessful` alert:
```
probe_success == on (instance) group_left min(probe_success) BY (instance) != 1
```

What do you think of this issue and the proposed solution?

**Comment by frodenas** [comment]
@aveyrenc LGTM
