### ISSUE TITLE
Can Prometheus and Alert manager can use CF UAA?

### ISSUE THREAD

**Issue by gmadu123** [bosh-prometheus/prometheus-boshrelease#217]
We have Grafana working with Cloud Foundry UAA(company LDAP integrated).  Is there anyway we can use Prometheus and Alert manager with UAA? if it can be achieved some other way please suggest.

**Comment by gmadu123** [comment]
Hi Guys, Any response on this will be helpfull.

**Comment by frodenas** [comment]
@gmadu123 No, it's not possible. Prometheus and Alertmanager don't have any authentication system. Actually, it's nginx who protects those components, and there isn't any integration between uaa and nginx.

**Comment by giva01121** [comment]
@frodenas what's the idea of the file https://github.com/bosh-prometheus/prometheus-boshrelease/commits/master/manifests/operators/cf/add-prometheus-uaa-clients.yml
If you can't use it for integration to CF UAA ?

**Comment by benjaminguttmann-avtq** [comment]
Hi @giva01121 !

That ops file is simply used for the exporter to authenticate itself against the UAA to access the system.
