### ISSUE TITLE
cf_exporter takes long to respond

### ISSUE THREAD

**Issue by manaspatkar21** [bosh-prometheus/prometheus-boshrelease#219]
Hi,
     I have a PCF foundation with several spaces/orgs. I observed that curl http://localhost:9193/alerts takes around 90 secs to respond back, hence the cf_exporter is marked down. What can be done to resolve this ?

**Comment by benjaminguttmann-avtq** [comment]
For large environments it is possible that the cf_exporter takes long to respond. It this case you can think about increasing the scrape interval and timeout for the cf_exporter. Afterwards you should be able to get data of the cf exporter again, and it should be marked as up.
