### ISSUE TITLE
Grafana dashboard

### ISSUE THREAD

**Issue by manaspatkar21** [bosh-prometheus/prometheus-boshrelease#220]
Hi,
   I created a custom dashboard in Grafana. I exported the dashboard and imported in the new environment, however the data never shows up in the new environment. I can see the data for the existing dashboards. The datasource name is "prometheus" in both environments. What could be going wrong ?

**Comment by frodenas** [comment]
How are you exporting/importing the dashboard? Saving it to a file or just copy/paste the the JSON?

**Comment by benjaminguttmann-avtq** [comment]
Maybe the Grafana version you exported the dashboard out of is newer than in the other environment? 
Dashboards of Grafana v5 are not compatible to older Grafana versions.
