### ISSUE TITLE
CloudFoundry Dashboard not working

### ISSUE THREAD

**Issue by lordcf** [bosh-prometheus/prometheus-boshrelease#221]
Hi @frodenas @benjaminguttmann-avtq i am facing this issue with Cloudfoundry dashboard where prometheus v22.0.2 and CF v1.36.0 is deployed. I can see all other dashboard i.e. bosh dashboard, Prometheus Dashboard etc...
When i check in CF dashboard i.e. CF:Cells Capacity or CF: BBS or anything in that way i am unable to see any data being populated.
Attaching the screenshot for the same:
![cf1](https://user-images.githubusercontent.com/25821409/41717353-1900241e-7577-11e8-8a94-cc40bd54742a.PNG)
![cf](https://user-images.githubusercontent.com/25821409/41717354-1938f302-7577-11e8-91c8-6c6c2ffdf0ad.PNG)

But as soon as i select CF:SpaceSummary or CF:Summary i can see data on the dashboard.
Prometheus metrics like cf_organization_info shows metrics also status-->target shows cf_exporter enabled.

Can you please let me know what can be the fix to get the CF dashboard working perfectly. 
FYI:
metron_deployment_name is same as metron_agent name.

**Comment by benjaminguttmann-avtq** [comment]
Hi,

perhaps and update to the newest Prometheus Version could solve the problem because a new version of the components dashboard was added for newer loggregator versions.
If you don't want to update you could import the JSON from this [URL](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/jobs/cloudfoundry_dashboards/templates/cf_component_metrics_v2.json) and check if you are able to see some metrics in there.

**Comment by benjaminguttmann-avtq** [comment]
There were two problems in this issue:

1. The loggregator version was not working with the old Component Metrics dashboard.
2. The v2 of the Component Metrics dashboard was not shown in Grafana because of duplicated title and uid. 
I will provide a PR to solve this.

**Comment by lordcf** [comment]
@benjaminguttmann-avtq do we have to make some more changes for cf_component_metrics_v2.json 
because as soon as i copied this file on the path /var/vcap/data/job/grafana/***/ i am getting the error on grafana dashboard as templates unavailable. Seems both the issue is with port availability.
Attaching the artifacts.
![grafana](https://user-images.githubusercontent.com/25821409/41765581-1bddbede-7622-11e8-9197-cc3370a846dc.png)
![boshdashboard](https://user-images.githubusercontent.com/25821409/41765582-1c0e6322-7622-11e8-83a8-c25ac5af8a4c.PNG)

**Comment by benjaminguttmann-avtq** [comment]
I think you should use the 'import' functionality of Grafana. 
So first remove the file you copied onto the disk and `monit restart grafana`.
Afterwards 

1. copy the whole json for the `Component Metrics v2` dashboard 
2. click on the Dashboard Dropdown inside Grafana 
3. Click on the `Import Dashboard` button on the right site
4. Copy JSON content into the text field
5. Click `load`

Now the dashboard should be available and loaded correctly.

**Comment by lordcf** [comment]
Umm even that did not helped me generating data on CF Component matrics. Only option i have is to upgrade it to the latest one i.e. 23.0 so get this things running

**Comment by benjaminguttmann-avtq** [comment]
Hi @lordcf ,

it seems like the cf_exporter uses a wrong password? 
At least that's what your cf exporter says.
Perhaps you should check this. 

It should be possible to authenticate with the uaa with the client_name `cf_exporter` and the client_secret.

**Comment by benjaminguttmann-avtq** [comment]
@lordcf : These metrics are gathered from the firehose exporter. 

The labels should be filled from the metric:

`firehose_value_metric_rep_unhealthy_cell`

**Comment by lordcf** [comment]
Unfortunately i dont see such metric "firehose_value_metric_rep_unhealthy_cell" in prometheus. I can get few values in CF dashboard like cf:space summary, cf:organization summary etc. But rest of the cf dashboard is not populating any kind of data. :(

**Comment by lordcf** [comment]
When checked the firehose vm got the below logs.

time="2018-06-27T09:57:32Z" level=error msg="Error getting oauth token: Received a status code 401 Unauthorized. Please check your Client ID and Secret." source="uaa_token_refresher.go:39"
time="2018-06-27T09:57:32Z" level=error msg="Error while reading from the Firehose: Received a status code 401 Unauthorized" source="firehose_nozzle.go:121"

seems issue with my UAA creds. Working on the same.

**Comment by lordcf** [comment]
Got the issue.  My droppler was risiding on wrong port. Due to which the connection was refused. Now when i gave the domain with port in monitor-cf.yml it worked for me.
Now all the dashboard are working fine.
Thanks @benjaminguttmann-avtq for your prompt reply :)

**Comment by lordcf** [comment]
@
