### ISSUE TITLE
prometheus job needs a web.external_url setting like alertmanager has 

### ISSUE THREAD

**Issue by matthewfischer** [bosh-prometheus/prometheus-boshrelease#224]
The prometheus job needs a web.external_url setting like alertmanager has. This is required so that the Source link in Alert Manager points to the right location rather than the bosh VM name.

**Comment by frodenas** [comment]
You can already set that property: https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/jobs/prometheus2/spec#L84. Is there anything missing?

**Comment by matthewfischer** [comment]
Just me missing it, thats all!
