### ISSUE TITLE
Refine Cf Cloud Controller dashboard & alerts with more capacity-related metrics

### ISSUE THREAD

**Issue by gberche-orange** [bosh-prometheus/prometheus-boshrelease#226]
We recently experienced an outage related to our blobstore (minio) capacity, which was not coping fast enough with diego requests to download droplets (in the scenario of a cold start of the whole CF deployment). As a result, this created a capacity issue on the cloudcontroller whose 20 threads started getting all busy on blobstore responses, and the API server began being slow, and being restarted by their health checks not completing within timeout.

The [CC capacity-related metrics](https://docs.cloudfoundry.org/running/all_metrics.html#cc) such as ``thread_info.event_machine.threadqueue.size`` (number of unscheduled tasks in the threadqueue)  would be useful to diagnose such CC capacity issues, along with a related alert.

![image](https://user-images.githubusercontent.com/4748380/42566146-ea1a7de0-8505-11e8-8ea4-4b3c1910c318.png)

**Comment by frodenas** [comment]
@gberche-orange Do you plan to contribute a dashboard and/or alerts for this?

**Comment by gberche-orange** [comment]
@frodenas we've added that to our backlog (see linked issue in paas-templates repo), but I can't tell how soon we'll be able to tackle this.
