### ISSUE TITLE
Incorrect usage of "web.enable-lifecycle" command-line flag

### ISSUE THREAD

**Issue by acho-bacho** [bosh-prometheus/prometheus-boshrelease#229]
I see that web.enable-lifecycle flag is enabled with 
prometheus --web.enable-lifecycle=VALUE
instead of 
prometheus --web.enable-lifecycle

https://github.com/bosh-prometheus/prometheus-boshrelease/blob/d72cc44abb3b9aaafaaabdec6bad3334bb669831/jobs/prometheus2/templates/bin/prometheus_ctl#L82

**Comment by frodenas** [comment]
Willing to submit a PR to fix it?

**Comment by acho-bacho** [comment]
sure

**Comment by frodenas** [comment]
Fixed at https://github.com/bosh-prometheus/prometheus-boshrelease/commit/113c801f7485db428ede6811b189951105cdcfb0.
