### ISSUE TITLE
incompatibility v23.1 with mysqld_exporter v0.11.00

### ISSUE THREAD

**Issue by ldangeard-orange** [bosh-prometheus/prometheus-boshrelease#233]
hi,
v23.1 prometheus-boshrelease use package v0.11.0 mysqld_exporter. 
In v0.11.0. you need to modify `prometheus-boshrelease/blob/master/jobs/mysqld_exporter/templates/bin/mysqld_exporter_ctl`  with changes the behavior of boolean flags.
```
    Enable: --collect.global_status
    Disable: --no-collect.global_status
```
and not
```
   Enable: --collect.global_status="true"
   Disable: --collect.global_status="false"
```
or use v0.10.0

**Comment by ldangeard-orange** [comment]
@benjaminguttmann-avtq 
From my point of view, the first solution is preferable, no modification spec file, and no modification of my MySQL deployment yml

**Comment by frodenas** [comment]
Fixed at https://github.com/bosh-prometheus/prometheus-boshrelease/commit/f29fb3ad0a83fc1294ff0f301f52a56cb8d26cd6.

**Comment by ldangeard-orange** [comment]
Thanks !

**Comment by ldangeard-orange** [comment]
I test it. It's OK.
