### ISSUE TITLE
proxy_url for alertmanager.yml

### ISSUE THREAD

**Issue by spdigitalpcfservice** [bosh-prometheus/prometheus-boshrelease#234]
From version 0.15.0 alertmanager does not honor the proxy variables set in env. Proxy has to be specified in the `alertmanager.yml` config file.

https://github.com/prometheus/alertmanager/issues/1300

**Comment by benjaminguttmann-avtq** [comment]
Do you mean the proxy_url which is configurable in https://prometheus.io/docs/alerting/configuration/#http_config ?

So this one will no longer work with the new alertmanager version (https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/manifests/operators/proxy/enable-proxy-alertmanager.yml) ?

**Comment by spdigitalpcfservice** [comment]
yes. the former has no effect anymore. our slack alerts stopped coming in once we bumped alertmanager to 0.15.0 (v23.1.0). Verified that its a proxy issue by manually adding http_config to alertmanager.yml and restarting alertmanager.

**Comment by benjaminguttmann-avtq** [comment]
Willing to submit a PR to fix it?

**Comment by spdigitalpcfservice** [comment]
I could give it a shot, but it will have to wait till after 2 weeks. got something else taking up my time till then. feel free to take care of it if you got enough bandwidth. thanks

**Comment by frodenas** [comment]
Fixed at https://github.com/bosh-prometheus/prometheus-boshrelease/pull/238 by @benjaminguttmann-avtq.
