### ISSUE TITLE
blackbox exporter issue

### ISSUE THREAD

**Issue by gmadu123** [bosh-prometheus/prometheus-boshrelease#236]
I am using prometheus 21.1.1 version with postgres 26. I am trying to add blackbox exporter.  when i try to give operation file "monitor-http-probe.yml" and with a probe_endpoints: https://google.com as a example i am getting below errors. Any help will appreciated.

[error_file_content.log](https://github.com/bosh-prometheus/prometheus-boshrelease/files/2263322/error_file_content.log)

**Comment by benjaminguttmann-avtq** [comment]
Hi @gmadu123,

I just tested your config with a yaml validation tool and it shows me valid yaml.
Maybe you could increase the log level of Prometheus to get more information.

**Comment by benjaminguttmann-avtq** [comment]
@gmadu123 Is the problem still existing ?

**Comment by frodenas** [comment]
Please reopen if the problem still persists.
