### ISSUE TITLE
How can clean up prometheus datas 

### ISSUE THREAD

**Issue by leolzbing521** [bosh-prometheus/prometheus-boshrelease#246]
![default](https://user-images.githubusercontent.com/5356341/45340693-2a26b080-b5ca-11e8-8cec-6150b2f8db63.png)
prometheus datas have use 61% presistent disk ,How can I clean up data.

**Comment by leolzbing521** [comment]
when I set prometheus.storage.local.retention In manifest/prometheus.yml ,is not work.

**Comment by benjaminguttmann-avtq** [comment]
@leolzbing521 For Prometheus2 the local retention config changed 

https://github.com/bosh-prometheus/prometheus-boshrelease/blob/8ddbbf39b97f088e5bdb806fad0ad3a326b1112b/jobs/prometheus2/spec#L63

**Comment by leolzbing521** [comment]
I use prometheus ,no prometheus2. 
prometheus.storage.local.retention  use yaml style wrong.  It is has  work.
