### ISSUE TITLE
alert=ConcourseHighWorkerContainers undefined variable \"$bosh_deployment\"

### ISSUE THREAD

**Issue by Alexvianet** [bosh-prometheus/prometheus-boshrelease#249]
Prometheus log spamming: error in alert rule ConcourseHighWorkerContainers

```
level=warn ts=2018-09-28T17:40:57.329459677Z caller=alerting.go:220 component="rule manager" alert=ConcourseHighWorkerContainers msg="Expanding alert template failed" err="error parsing template __alert_ConcourseHighWorkerContainers: template: __alert_ConcourseHighWorkerContainers:1: undefined variable \"$bosh_deployment\"" data="unsupported value type"
```

concourse_workers_containers mectric contain only:

```
concourse_workers_containers{instance="10.00.00.102:9391",job="concourse",platform="linux",worker="07ebfb4a-3c86-40f8-9b26-057000008b"}
```

**Comment by frodenas** [comment]
This has been fixed at https://github.com/bosh-prometheus/prometheus-boshrelease/pull/245. I'll cut a new bosh release with this patch pretty soon.

The `bosh_deployment` label is added at the [scrape config](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/manifests/operators/monitor-bosh.yml#L173).

**Comment by Alexvianet** [comment]
thanks
