### ISSUE TITLE
Enable and configure blackbox exporter

### ISSUE THREAD

**Issue by Murugan2all** [bosh-prometheus/prometheus-boshrelease#250]
Please share the steps to enable and configure blackbox exporter with Prometheus with this existing pipeline.

**Comment by frodenas** [comment]
You can use the [monitor-http-probe.yml](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/manifests/operators/monitor-http-probe.yml) opfile as an example of how to enable the `blackbox_exporter`.
