### ISSUE TITLE
Thanos bosh-job

### ISSUE THREAD

**Issue by bkez322** [bosh-prometheus/prometheus-boshrelease#252]
It would be fantastic if [Thanos](https://github.com/improbable-eng/Thanos) were to be a part of this release.

Thanos is a side-component to Prometheus, and [particularly useful in large scale environments](https://improbable.io/games/blog/thanos-prometheus-at-scale).

Specifically, what Thanos would add to this release include:
- Long-term storage with automatic downsampling (Prometheus itself isn’t designed to store data for more than a few weeks).
- Improved HA (Without Thanos, even if you run multiple redundant Prometheus instances, an instance that was down and came back up will always give you “holes” in your graphs).
- Automatic global-view federation (this is especially useful for those of us with multiple CF and BOSH environments).

**Comment by frodenas** [comment]
@bkez322 Please see the [Thanos BOSH release](https://github.com/bosh-prometheus/thanos-boshrelease) in this github borg.
