### ISSUE TITLE
Please share the steps to add dashboard for "firehose_counter_event_loggregator_metron_dropped_total" rule in grafana.

### ISSUE THREAD

**Issue by ranjithfd** [bosh-prometheus/prometheus-boshrelease#253]
Please share the steps to add dashboard for "firehose_counter_event_loggregator_metron_dropped_total" rule in grafana.

Basically we can see the output when we try to execute this  query in prometheus, so we need to add the following rule into grafana dashboard.

plz share the step.

**Comment by frodenas** [comment]
You can create (or edit) a grafana dashboard and add a graph for that metric by following this doc: [Creating a Prometheus graph](https://prometheus.io/docs/visualization/grafana/#creating-a-prometheus-graph)
