### ISSUE TITLE
for bosh concourse

### ISSUE THREAD

**Issue by gmadu123** [bosh-prometheus/prometheus-boshrelease#255]
Hi,

I have 2 bosh directors one is hosting PCF platform other one is standalone bosh director. In standalone bosh director i have concourse, Prometheus installed. May i know how to moniter standlone bosh managed concourse, I did not understand where and how i need to add below lines

# Apply to your concourse-deployment

# Enable prometheus metrics
- type: replace
  path: /instance_groups/name=web/jobs/name=atc/properties/prometheus?
  value:
    bind_ip: 0.0.0.0
    bind_port: 9391

**Comment by frodenas** [comment]
This should be applied to your concourse deployment. It basically updates the `atc` job to enable the internal prometheus metrics.

**Comment by frodenas** [comment]
Please reopen if you still have questions.
