### ISSUE TITLE
Customer Scrap Config

### ISSUE THREAD

**Issue by ranjithfd** [bosh-prometheus/prometheus-boshrelease#256]
Hi,

I wanted to create new custom scrap config to our internal spring boot app using https protocol. when i try to update the metrics and "https" scheme  in prometheus.yml file, its end up with error. 

please share the steps to configure custom scrap config

**Comment by benjaminguttmann-avtq** [comment]
Hi @ranjithfd ,

could you add some code snippet to the issue ? 

Thanks

**Comment by ranjithfd** [comment]
Hi benjamin,

    thanks for you reply, Please advise how to configure new custom metrics in prometheus to collect data from the URL.
  basically below mentioned metrics is not available in default prometheus metrics to pull the data from URL.
eg: http_request_duration_microseconds



Please check my code below:-
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus/properties/prometheus/scrape_configs/-
  value:      
    job_name: 'testf'
    scrape_interval: 10s
    metrics_path: '/metrics'
    scheme: 'http'
    params:
       format: ['text']
       module:
        - http_2xx
    static_configs:
      - targets: ['https://********/text/file']
        labels:
          group: 'test'
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: localhost:9090

**Comment by benjaminguttmann-avtq** [comment]
First thing I see is that you define the scheme `'http'` (instead of `'https'`) and in the targets setting you should leave out the `http/https`... if you changed that and it is still not working you can either check the logs of prometheus for some errors or `curl` the exporter `/metrics` endpoint to perhaps get an error log or something like that.

**Comment by ranjithfd** [comment]
Hi Mate,

         I have updated the same parameter as you mentioned above, but i got below mentioned error.

Get https://localhost:9090/metrics?target=******.com%2: http: server gave HTTP response to HTTPS client.

Now, am planning to create new custom metrics like below. Please help me to create.

http_server_requests_seconds_sum{cfInstanceId="0",cfSpace="performance",exception="None",method="GET",status="200",uri="/metrics",}

**Comment by benjaminguttmann-avtq** [comment]
Closed due to inactivity; Please feel free to re-open if issue still persists
