### ISSUE TITLE
grafana syntax issues

### ISSUE THREAD

**Issue by gmadu123** [bosh-prometheus/prometheus-boshrelease#257]
When i try to deploy proemthes 23.3.0 release along with grafana UAA i am getting below error. Can u please let me know what might be issue?

My command:

bosh -e bosh-eng -d prometheus deploy prometheus.yml   -l prometheus-vars.yml   -o operators/enable-grafana-uaa.yml 

error:

22:21:16 | Error: Unable to render instance groups for deployment. Errors are:
  - Unable to render jobs for instance group 'grafana'. Errors are:
    - Unable to render templates for job 'grafana'. Errors are:
      - Failed to fetch variable '/bosh-engomahastandlone/prometheus/uaa_ssl' from config server: Invalid JSON response
      - Failed to fetch variable '/bosh-engomahastandlone/prometheus/uaa_ssl' from config server: Invalid JSON response
      - Failed to fetch variable '/bosh-engomahastandlone/prometheus/uaa_ssl' from config server: Invalid JSON response

**Comment by gmadu123** [comment]
I am passing below variables through my vars file

uaa_ssl.ca: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
uaa_ssl.certificate: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
uaa_ssl.private_key: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----

**Comment by frodenas** [comment]
Please reopen if this is still an issue for you.
