### ISSUE TITLE
prometheus upgrade

### ISSUE THREAD

**Issue by gmadu123** [bosh-prometheus/prometheus-boshrelease#258]
May i know what is the best way to upgrade from bosh prometheus 21.1.0 to 23.3.0 with out loosing any data from the db

**Comment by gmadu123** [comment]
Any update will be appreciated and help full.

**Comment by Alexvianet** [comment]
,ф

**Comment by Alexvianet** [comment]
run second prometheus 23.3.0 for rotation  period and then switch grafana to the new one

**Comment by Alexvianet** [comment]
also check documentation  there is also some solutions

**Comment by frodenas** [comment]
Release notes for [v22.0.0](https://github.com/bosh-prometheus/prometheus-boshrelease/releases/tag/v22.0.0) contains detailed instructions on how to upgrade prometheus.
