### ISSUE TITLE
Monitor Certificate based URLs using blackbox exporter

### ISSUE THREAD

**Issue by Murugan2all** [bosh-prometheus/prometheus-boshrelease#262]
Hi Team

I am trying to monitor the URL which is authenticated using certificate. If i hit the URL, certificate will prompt and then authentication will happen. If i try to curl -I <url>, received a 401 Authorization response code from prometheus node. 

So i added the 401 in the valid_status_codes: []. Still the URL is down in Grafana. Please let me know if i need to do any more modification to monitor certificate based URLs.

**Comment by frodenas** [comment]
You need to add [tls_config](https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md#tls_config) section at the [http_probe](https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md#http_probe) configuration with the authentication certs.
