### ISSUE TITLE
URLs should pass through Proxies in Blackbox exporter

### ISSUE THREAD

**Issue by Murugan2all** [bosh-prometheus/prometheus-boshrelease#263]
Hi Team

I need to monitor external URLs which can access only through proxy. So i enabled proxy_url in monitor-http-probe.yml and still the status in down in Grafana.

How to make all URLs to pass through proxies in blackbox exporter. 

Regards
Murugan D

**Comment by poblin-orange** [comment]
Hello. We have the same issue. afraid their is an issue in prometheus blackbox exporter itself, that does not support correcly http/https proxy, see https://github.com/orange-cloudfoundry/paas-templates/issues/241
