### ISSUE TITLE
Monitor ORG wise in Prometheus & dashboard view in Grafana

### ISSUE THREAD

**Issue by Murugan2all** [bosh-prometheus/prometheus-boshrelease#266]
Hi Team

We need to monitor the ORG wise monitoring in Prometheus and all information about the ORG(For ex-Org, space and Apps related information) should be listed in Grafana.

Regards
Murugan D

**Comment by benjaminguttmann-avtq** [comment]
Closed due to inactivity; Please feel free to re-open if issue still persists
