### ISSUE TITLE
ubuntu-xenial as default stemcell

### ISSUE THREAD

**Issue by gdenn** [bosh-prometheus/prometheus-boshrelease#268]
Hi,

i saw that you have the ubuntu-trusty os still in the prometheus bosh deployment manifest under default stemcell.
Maybe you can switch to xenial already since LTS support of trusty ends at April 2019.

I tested a deployment of prometheus on vSphere with xenial (170.5) and had no problems.

https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/manifests/prometheus.yml#L172

best,
D

**Comment by gdenn** [comment]
PR: https://github.com/bosh-prometheus/prometheus-boshrelease/pull/269

**Comment by frodenas** [comment]
PR #269 has been merged, so default stemcell is now Xenial.
