### ISSUE TITLE
Make individual alerts disable-able

### ISSUE THREAD

**Issue by richardTowers** [bosh-prometheus/prometheus-boshrelease#272]
## Context

At the moment users of prometheus-boshrelease are able to configure thresholds and evaluation times for alerts, but not much else.

For example, if you wanted to exclude the diego cells from a CPU alert you would need to edit the `expr:` itself. Similarly, if you
want to replace an alert it's not possible to remove alerts in this boshrelease with an ops file.

## A modest proposal

Wrap each alert in a conditional so that they can be disabled and replaced with custom alerts.
Introduce a new variable in the alerts jobs where you can list the alerts you want to disable.

**Comment by frodenas** [comment]
Sounds good to me, are you willing to submit a PR with those changes? :)

**Comment by richardTowers** [comment]
Yep, I'll have a look.
