### ISSUE TITLE
RPS in CF "Apps: Requests" dashboard is not correct

### ISSUE THREAD

**Issue by prolane** [bosh-prometheus/prometheus-boshrelease#276]
We've noticed the Cloudfoundry "Apps: Requests" dashboard voor Grafana is not correct on the requests per second (RPS). I'm referring to this dashboard: https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/jobs/cloudfoundry_dashboards/templates/cf_apps_requests.json

To be more specific, I'm referring to the graphs which are using the `firehose_http_start_stop_requests` metric.

We've noticed the RPS graph is not correct. Its the rate() function used with this metric which is causing the unexpected results. I've been in touch with the prometheus community to verify and this is also where you can read my investigation:
https://groups.google.com/forum/#!msg/prometheus-users/Ju3CjMT7gTI/VLOOeIYCDAAJ

In summary the `firehose_http_start_stop_requests` metric is a gauge type metric while the `rate()` function is meant for counter type metrics.

Currently my own solution at this time is to change this:
`avg(rate(firehose_http_start_stop_requests{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"}[5m]))`

to this:
`sum(firehose_http_start_stop_requests{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"})/300`

You can see the difference on the screenshots in the Google groups link I shared.

The reason why I have to divide by 300 is because of this setting: `firehose_exporter.doppler.metric_expiration` which has a default of 5 minutes.
https://github.com/bosh-prometheus/firehose_exporter/blob/76b9c9fd1d4a3b1dbc900072d375cbf2a71e13e8/firehose_exporter.go#L60

So to change the prometheus query properly we should be make this metric_expiration a variable in the prometheus-boshrelease so both the `prometheus_exporter` job as well as the `cloudfoundry_dashboards` job can use it.

What do you guys think?

**Comment by frodenas** [comment]
Sounds good, willing to update this via PR?

**Comment by prolane** [comment]
I am @frodenas, but before I do, lets discuss this question: https://github.com/bosh-prometheus/firehose_exporter/issues/41
