### ISSUE TITLE
Update Graphite Exporter 

### ISSUE THREAD

**Issue by kfkonrad** [bosh-prometheus/prometheus-boshrelease#281]
Is it possible to update graphite exporter to a later version, like v0.4.2 (currently v0.2.0 is being used)? This would be a breaking change in the bosh release btw, as v0.3.0 introduces a yaml based config format.

**Comment by frodenas** [comment]
Updated at https://github.com/bosh-prometheus/prometheus-boshrelease/commit/1b39c6f6560180dbcb9ad56a67a544498543a54a. I'll cut a new release soon.
