### ISSUE TITLE
After Prometheus upgrade from 21.1. to 23.3 not reflect CF and Bosh in Prometheus portal

### ISSUE THREAD

**Issue by vinodh19** [bosh-prometheus/prometheus-boshrelease#283]
After Prometheus upgrade from 21.1. to 23.3 using Github/Prometheus-boshrelease, CF and Bosh related alerts not reflected in Prometheus portal. But we are able to see P-Redis, P-RabbitMQ, Postgres  and Prometheus related alerts in Prometheus portal.

Attached the YAML file for CF and Bosh for reference.

**Comment by vinodh19** [comment]
[Yaml File.zip](https://github.com/bosh-prometheus/prometheus-boshrelease/files/2787940/Yaml.File.zip)

**Comment by benjaminguttmann-avtq** [comment]
Closed due to inactivity; Please feel free to re-open if issue still persists
