### ISSUE TITLE
Trying to externalize alertmanager smtp & route params  

### ISSUE THREAD

**Issue by spkrsna** [bosh-prometheus/prometheus-boshrelease#284]
I have created a file under  operators/monitor-smtp-use-vars.yml folder with the below contents 
- type: replace
  path: /instance_groups/name=alertmanager/jobs/name=alertmanager/properties/alertmanager/route/receiver/name=default?/-
  value:
    group_by: [job]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h

**while trying to deploy receiving the following errors**

Using deployment 'prometheus'
Evaluating manifest:
  Expected to find an array at path '/instance_groups/name=alertmanager/jobs/name=alertmanager/properties/alertmanager/route/receiver/name=default' but found 'string'

Exit code 1

**Comment by mylucidreality** [comment]
These values are actually at the same level as receiver.  See if this helps
Ex.
        properties:
          alertmanager:
            route:
              receiver: default
              group_by:
              - alertname
              group_interval: 15m
              group_wait: 5m
              repeat_interval: 8h
              severity: critical

**Comment by spkrsna** [comment]
Thanks! for the response , but still facing the same error and sharing snaps of the same. To elaborate on the issue if i place the above params & values in  prometheus.yml it is deploying
Ex: alertmanager section from prometheus.yml file
jobs:
      - name: alertmanager
        release: prometheus
        properties:
          alertmanager:
            smtp:
              resolve_timeout: 5m
              smarthost: ((smtp_smarthost))
              from: ((mail_from))
              require_tls: false
           route:  
              receiver: default     
            #receivers:
            #  - name: default           
            route:
              group_by: [job]
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 12h
            receivers:
            - name: default
              email_configs:
              - to: test@example.com
                require_tls: false
            test_alert:
              daily: true

but when i try to use a externalize file under extra_ops/monitor-smtp-use-vars.yml and calling using the -o option facing the below error 

Using deployment 'prometheus'

Evaluating manifest:
  Expected to find an array at path '/instance_groups/name=alertmanager/jobs/name=alertmanager/properties/alertmanager/route/-' but found 'map[interface {}]interface {}'

Exit code 1

**Comment by spkrsna** [comment]
Any idea on how to externalize email params for alertmanager will be helpful

**Comment by benjaminguttmann-avtq** [comment]
@spkrsna 
For your initial try
```
type: replace
path: /instance_groups/name=alertmanager/jobs/name=alertmanager/properties/alertmanager/route/receiver/name=default?/-
value:
group_by: [job]
group_wait: 30s
group_interval: 5m
repeat_interval: 12h
```

It looks to me like your indention is wrong. The whole part below value needs to be indented by two spaces, before the type you need to add a `-` and add indention to path and value as well, and the configuration you try to add should be below route, so I guess the ops file should look like the following:

```
- type: replace
  path: /instance_groups/name=alertmanager/jobs/name=alertmanager/properties/alertmanager/route/group_by?
  value: [job]

- type: replace
  path: /instance_groups/name=alertmanager/jobs/name=alertmanager/properties/alertmanager/route/group_wait?
  value: 30s

- type: replace
  path: /instance_groups/name=alertmanager/jobs/name=alertmanager/properties/alertmanager/route/group_interval?
  value: 5m

- type: replace
  path: /instance_groups/name=alertmanager/jobs/name=alertmanager/properties/alertmanager/route/repeat_interval?
  value: 12h
```

**Comment by spkrsna** [comment]
Thanks! will check and let u know!
