### ISSUE TITLE
Pull in latest cf_exporter update when/if ready

### ISSUE THREAD

**Issue by DRuggeri** [bosh-prometheus/prometheus-boshrelease#286]
Hi there. I have an open PR for `cf_exporter` that will add events API support.
https://github.com/bosh-prometheus/cf_exporter/pull/28

When/if that is merged, this boshrelease should be updated to pull the new release in.

I am happy to do legwork on either repo to make it happen.

**Comment by frodenas** [comment]
Prometheus BOSH release [v26.0.0](https://github.com/bosh-prometheus/prometheus-boshrelease/releases/tag/v26.0.0) contains the latest cf_exporter.
