### ISSUE TITLE
Add ability to filter service discovery targets in the same availability zone

### ISSUE THREAD

**Issue by bandesz** [bosh-prometheus/prometheus-boshrelease#287]
## What

We want to be able to set up a scrape configuration where targets would be used from the same AZ only where the Prometheus instance is deployed.

It's important to note that we can't use the `filter.azs` option, as we still want to scrape most of the targets from all AZs. We want to filter per scrape_config.

Currently the bosh-exporter doesn't include the AZ in the generated `bosh_target_groups.json` and even if it did I don't know whether it's possible to filter dynamically for the same AZ in the relabel config.

## Use case

We deploy Prometheus in HA (but without federation), which means every component is running on two instances in separate AZs. We have a problem with the firehose-exporter as both Prometheus instances scrape both firehose-exporters which duplicates all metrics. We want to avoid this and each Prometheus instance should scrape the firehose-exporter in the same AZ only.

## Ideas

* If a certain flag is enabled the bosh-exporter could generate an extra file which would contain instances from the same AZ only. In this case we could point file_sd_config to this new file. (Maybe this could be enabled by default as it's a new file)
* Add the AZ to the `bosh_target_groups.json` and add the ability to filter by the same AZ for a scrape config. For this we might need to come up with some clever templating tricks or maybe even a new Bosh job?

**Comment by bandesz** [comment]
We decided to create a custom `service_discovery` BOSH job which can generate service discovery files with AZ affinity. I opened a PR as it might be useful for other people too: https://github.com/bosh-prometheus/prometheus-boshrelease/pull/290

**Comment by frodenas** [comment]
PR #290 merged
