### ISSUE TITLE
Add option to nginx job to disable cross zone load balancing

### ISSUE THREAD

**Issue by bandesz** [bosh-prometheus/prometheus-boshrelease#289]
## What

Currently the nginx job will add all Prometheus, Alertmanager and Grafana instances to the upstream configurations. We want to be able to tell nginx that it should only forward requests to instances in the same availability zone.

## Why

We are deploying Prometheus in an HA setup, so we have two independent clusters in two availability zones. We want to disable any cross-zone load balancing so we always know which servers are we communicating with.

## Pull request

https://github.com/bosh-prometheus/prometheus-boshrelease/pull/288

**Comment by frodenas** [comment]
#288 has been merged.
