### ISSUE TITLE
Allow to set a unique subscription id for the firehose-exporter

### ISSUE THREAD

**Issue by bandesz** [bosh-prometheus/prometheus-boshrelease#292]
## What

Allow to set a unique subscription id for the firehose-exporter.

Currently there is no way to deploy multiple instances of the firehose-exporter and have a unique subscription id. We need all firehose exporters to receive all events.

## Pull requests

* https://github.com/bosh-prometheus/prometheus-boshrelease/pull/291

**Comment by frodenas** [comment]
Fixed at https://github.com/bosh-prometheus/prometheus-boshrelease/pull/291
