### ISSUE TITLE
Retention property needs to be updated

### ISSUE THREAD

**Issue by bkez322** [bosh-prometheus/prometheus-boshrelease#296]
As of Prometheus v2.7 the startup property `--storage.tsdb.retention` has been deprecated in favor of `--storage.tsdb.retention.time`.

https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects

**Comment by frodenas** [comment]
Fixed at https://github.com/bosh-prometheus/prometheus-boshrelease/pull/297
