### ISSUE TITLE
Generate dashboard and alerts for CF component metrics from Indicator Protocol

### ISSUE THREAD

**Issue by gberche-orange** [bosh-prometheus/prometheus-boshrelease#299]
The monitoring-indicator-protocol (see https://github.com/pivotal/monitoring-indicator-protocol/wiki ) is a format proposed by the cloudfoundry/pivotal teams, which enables core CF components to complete their metrics with expected normal values ranges, as well as abnormal ranges associated with alert definitions. 

This enables CF component teams that know best the target SLI for their component to maintain such business dashboards and alerts (e.g. #226 for CAPI team). According to @jtuchscherer (sharing about indicator protocol at cf summit philly 2019 unconference), adoption in CF component is in progress with loggregator team implemented it and diego team starting. See https://github.com/search?q=indicators.yml+in%3Apath+user%3Acloudfoundry&type=Code 

The [indicator-format](https://github.com/pivotal/monitoring-indicator-protocol/wiki#generate-docs) command can generate Grafana JSON dashboard, and prometheus alerting rules from an indicator protocol yml file.

The monitoring-indicator-protocol repo [provides a mechasnism](https://github.com/pivotal/monitoring-indicator-protocol/wiki#bosh-environments) to distribute indicator protocol files shipped within CF component bosh releases so that they'd be available to prometheus, see [indicator-registration-agent](https://github.com/pivotal/monitoring-indicator-protocol/blob/master/bosh-release/jobs/indicator-registration-agent/spec) and [indicator-registry](https://github.com/pivotal/monitoring-indicator-protocol/blob/master/bosh-release/jobs/indicator-registry/spec) 

It would be great to be able to leverage this mechanism to Generate dashboards and alerts for CF component metrics from Indicator Protocol

/CC  @psycofdj

**Comment by joerodriguez** [comment]
@gberche-orange Happy to pair on this, how would you like to proceed?

**Comment by aegershman** [comment]
If you don't mind me asking, did this fizzle out because of lack of interest, or because a hindrance was discovered that would prevent this from proceeding (or otherwise being a huge pain)?

**Comment by gberche-orange** [comment]
Sorry for late reply on this. @joerodriguez  I'm unfortunately lacking golang skills to pair on this. 

However, @aegershman, I understand from the [cf-for-k8s Metrics Guide](https://docs.google.com/document/d/1XdkqIJ2SeqajNyzyTOjLg_VjuatSTCtown4-0xZEH3Q/edit) that CF4K8S components include automatically generated dashboards from indicator protocol, and possibly tailored dashboards per component. 

Might be worth looking for progress in this direction. Please keep this issue updated if you find some related progress.

**Comment by benjaminguttmann-avtq** [comment]
Closed due to inactivity; Please feel free to re-open if issue still persists
