### ISSUE TITLE
[Question] Redis_exporter upgrade to latest version

### ISSUE THREAD

**Issue by Alexvianet** [bosh-prometheus/prometheus-boshrelease#303]
Can we update  redis_exporter to the latest version? the reason is:
https://github.com/oliver006/redis_exporter/issues/257#issuecomment-490314007

**Comment by Alexvianet** [comment]
@frodenas it's possible to update Redis_exporter  to https://github.com/oliver006/redis_exporter/releases/tag/v1.0.0

**Comment by frodenas** [comment]
Updated at https://github.com/bosh-prometheus/prometheus-boshrelease/commit/b41055e8e685b66d3e9cd9c0a497a7a2d67de507.
