### ISSUE TITLE
what should be the value for firehose_exporter.logging.url

### ISSUE THREAD

**Issue by sfrancies** [bosh-prometheus/prometheus-boshrelease#304]

**Comment by sfrancies** [comment]
firehose_exporter.logging.url is this variable added new

**Comment by frodenas** [comment]
Either the doppler URL `wss://doppler.system_domain:traffic_controller_external_port` or the [RLP gateway](https://github.com/cloudfoundry/loggregator-release#rlp-gateway) URL `https://log-stream.system_domain`
