### ISSUE TITLE
Add ability to use VictoriaMetrics as long term remote storage

### ISSUE THREAD

**Issue by valyala** [bosh-prometheus/prometheus-boshrelease#308]
It would be great to be able to configure VictoriaMetrics as long-term remote storage for `prometheus-boshrelease`. VictoriaMetrics has the following features:

- It is easy to configure and operate - it is just a single binary with small configs.
- It provides better compression ratio for the data comparing to other remote storage solutions. This means more data may be stored on the limited disk space.
- It requires less RAM and CPU comparing to competitors. This reduces hardware costs and improves query speed.
- It supports PromQL, so it can be used as a drop-in replacement for Prometheus datasource in Grafana.
- It can collect data from multiple Prometheus instances, so later the data may be queried at once (aka global querying view).

Read more info about VictoriaMetrics at [this page](https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/Single-server-VictoriaMetrics).

**Comment by Infra-Red** [comment]
Hi @valyala ! It's possible to configure external storage for `prometheus-boshrelease`. Both `remote_read` and `remote_write` properties could be configured for deployments.

https://github.com/bosh-prometheus/prometheus-boshrelease/blob/774725ecd80594602c4b50595ee9b07be3f5487e/jobs/prometheus2/spec#L50-L53

**Comment by valyala** [comment]
Great! The closing the issue.
