### ISSUE TITLE
Notice:  Missing metric tags in cf-deployment v9.0.0

### ISSUE THREAD

**Issue by jmprice** [bosh-prometheus/prometheus-boshrelease#309]
cf-deployment v9.0.0 which contains Loggregator Agent v3.9 with default deployment options to disable UDP listener on the loggregator agent (https://github.com/cloudfoundry/cf-deployment/blob/v9.0.0/cf-deployment.yml#L23-L24) is missing the DEPLOYMENT, JOB, INDEX, and IP tags for any metric still emitted via UDP.

The instances which contain jobs still using UDP are:  api, router, and tcp-router, cell, and scheduler

It looks like this has been addressed in a later release of the Loggrator Agent but hasn't been pulled into the cf-deployment yet:  https://github.com/cloudfoundry/loggregator-agent-release/commit/031c110aa0f04df9eb1544da7af783b44bf7100a

**Comment by benjaminguttmann-avtq** [comment]
Issue was actually introduced with version [v7.11](https://github.com/cloudfoundry/cf-deployment/releases/tag/v7.11.0) of the cf-deployment. The issue was still not solved.

**Comment by benjaminguttmann-avtq** [comment]
Issue was fixed with cf-deployment version 10.0.0
