### ISSUE TITLE
stackdriver_exporter typo in properties

### ISSUE THREAD

**Issue by shinmyung0** [bosh-prometheus/prometheus-boshrelease#313]
There seems to be a typo here. 

https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/jobs/stackdriver_exporter/templates/bin/stackdriver_exporter_ctl#L46

It should be `drop_delegated_projects` according to the documentation at 

https://www.bosh.io/jobs/stackdriver_exporter?source=github.com/cloudfoundry-community/prometheus-boshrelease&version=25.0.0#p%3dstackdriver_exporter.monitoring.drop_delegated_projects

**Comment by frodenas** [comment]
Fixed at https://github.com/bosh-prometheus/prometheus-boshrelease/commit/51ac601f97b731cf3ed5061a783ce12d158b41c4. Thanks for reporting this.
