### ISSUE TITLE
Clean deployment of v25.0.0 fails on bpm not being build for stemcel 250.4

### ISSUE THREAD

**Issue by aryanet** [bosh-prometheus/prometheus-boshrelease#314]
When tried to deploy prometheus-boshrelease v25.0.0, the deployment failed with this error:

Task 76009 | 01:14:03 | Preparing deployment: Preparing deployment (00:00:03)
Task 76009 | 01:14:06 | Preparing deployment: Rendering templates (00:00:03)
Task 76009 | 01:14:09 | Error:
Can't use release 'bpm/1.0.4'. It references packages without source code and are not compiled against stemcell 'bosh-aws-xen-hvm-ubuntu-xenial-go_agent/250.4':

'bpm/d7c8de76cea8201f6cdf37d4f848b0a52c9c5798'

'bpm-runc/cb758414ed267820880c6bf1ca57d7467c2d70bf'

'golang/b348840d6ee6de87fdd43e4792fdbe1af734039b'

Task 76009 Started Wed Jun 5 01:14:03 UTC 2019
Task 76009 Finished Wed Jun 5 01:14:09 UTC 2019
Task 76009 Duration 00:00:06
Task 76009 error

Updating deployment:
Expected task '76009' to succeed but state is 'error'

Exit code 1

Rolling back the stemcell to 170.21, works.

**Comment by benjaminguttmann-avtq** [comment]
@aryanet : Hi I saw this error if a deployment used a pre-compiled version of a release and deploying another deployment using the same release afterwards. Uploading the respective `bpm`release with the following command should fix the issue (forces the release to get compiled again).

`bosh upload-release https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=1.0.4 --sha1 41df19697d6a69d2552bc2c132928157fa91abe0 --fix`

**Comment by aryanet** [comment]
Thank you @benjaminguttmann-avtq. That helps. What I ended up doing was to create-release for bpm with a specific version tag from the source repo and it also worked.
