### ISSUE TITLE
Prometheus generates RESOLVED alert when VM is missing

### ISSUE THREAD

**Issue by Infra-Red** [bosh-prometheus/prometheus-boshrelease#315]
Hi All!

I've configured my deployment to use AWS Spot Instances and today I noticed the following:

1. Spot bid price has been changed and Diego Cell instance was destroyed in EC2.
1. I've received the following alert for the missing instance:
   ```
   FIRING:1 BOSH Job `my-env/bosh-my-env/cf/diego-cell/0` is unhealthy\n
   BOSH Job `my-env/bosh-my-env/cf/diego-cell/0` is being reported unhealthy
   ```
1. And in couples of minutes I've received RESOLVED alert for this issue:
   ```
   RESOLVED BOSH Job `my-env/bosh-my-env/cf/diego-cell/0` is unhealthy\n
   BOSH Job `my-env/bosh-my-env/cf/diego-cell/0` is being reported unhealthy
   ```
1. I've checked deployment VMs and `diego-cell/0` instance was missing in the VMs list.
   ![](https://i.imgur.com/8OGzGth.png)

1. BOSH scan and fix task result:
   ```
   bosh task 173083
   Using environment 'https://10.10.63.6:25555' as client 'admin'

   Task 173083

   Task 173083 | 15:14:10 | Scanning 1 VMs: Checking VM states (00:00:12)
   Task 173083 | 15:14:22 | Scanning 1 VMs: 0 OK, 0 unresponsive, 1 missing, 0 unbound (00:00:00)
   Task 173083 | 15:14:22 | Applying problem resolutions: VM for 'diego-cell/9c0f9d0d-a131-4fd0-9611-27b4b62598ba (0)' missing. (missing_vm 382): Recreate VM and wait for processes to start (00:04:37)
                      L Error: CPI error 'Bosh::Clouds::VMCreationFailed' with message 'Spot instance creation failed: #<Bosh::Clouds::VMCreationFailed: Timed out waiting for spot request #<struct Aws::EC2::Types::RequestSpotInstancesResult
   ```

**Expected behaviour**: Prometheus must still send FIRING alerts for missing VMs.

Is it a problem with how BOSH discovery works? AFAIU bosh_exporter expects to see all relevant VMs in `bosh vms` list and that's why I received RESOLVED alert for missing VM.

**Comment by benjaminguttmann-avtq** [comment]
@Infra-Red :  You are right, you received a RESOLVED because there is not failing/unresponsive agent in the bosh vms list. Maybe using the graphite exporter and the director health manager plugin could detect such as state but i am not sure about that

**Comment by Infra-Red** [comment]
@benjaminguttmann-avtq Thanks for the tip! I will try with `graphite_exporter`, hopefully this will help.

**Comment by benjaminguttmann-avtq** [comment]
@Infra-Red : This might help with configuring the `graphite_exporter` => https://github.com/bosh-prometheus/bosh_tsdb_exporter/issues/1
