### ISSUE TITLE
Grafana dashboard Update Interval Time

### ISSUE THREAD

**Issue by Muruganfly03** [bosh-prometheus/prometheus-boshrelease#320]
Hi Team

 We deployed Prometheus-boshrelease(v23.3.0) in our environment. We need to know the below information related to Grafana.

1. How frequent/Time interval in which data will be updated to Grafana dashboard?
2. Is there is any file in which Interval time to update Grafana dashboard is configured?

**Comment by Infra-Red** [comment]
Hi @Muruganfly03 ! Default scrape interval for Prometheus datasource is 15s.
https://github.com/grafana/grafana/blob/fcdc29746f41570fd2541616cc94244f94e9ad0b/public/app/plugins/datasource/prometheus/datasource.ts#L76

Currently it's not possible to update Grafana scrape interval for Prometheus datasource using job properties, `jsonData` field allows to configure only `tlsSkipVerify` param.
https://github.com/bosh-prometheus/prometheus-boshrelease/blob/e96d2f275e635b5d3c49a6905dc5a6a7f2be03cb/jobs/grafana/templates/config/provisioning/datasources/prometheus.yml#L35-L38

Also Grafana doesn't allow manual modifications for datasources that are created using the config. So you may want to create a PR if this is something that is really important for your environment.
