### ISSUE TITLE
graphite.mapping-strict-match does not support parameters

### ISSUE THREAD

**Issue by andinod** [bosh-prometheus/prometheus-boshrelease#323]
Hi

I'm trying to use the option mapping_strict_match in our prometheus deployment but then I've realized that this option for the graphite exporter doesn't receive any parameter but in the template's job  is a requirement to add it, as you can see in the code. If I define any value on this I will receive the error for the graphite_exporter like this:
graphite_exporter: error: unexpected true, try --help
    
This is the code:     
    <% if_p('graphite_exporter.graphite.mapping_strict_match') do |mapping_strict_match| %> \
      --graphite.mapping-strict-match="<%= mapping_strict_match %>" \
      <% end %> \

**Comment by benjaminguttmann-avtq** [comment]
Hi @andinod, 

I think you are right. The `="<%= mapping_strict_match %>"` part is not needed here.

Willing to update this via PR?

**Comment by andinod** [comment]
Hi Benjamin,

Thanks for your answer. Ok let me see if tomorrow I can make the change and create the PR. Unless somebody else could make it before. :-)

**Comment by andinod** [comment]
Hi Benjamin,

Sorry but I couldn't create the PR due to I'm not a contributor, and due to this I could upload the branch and specify the changes. If you please can add it I would appreciate it.

**Comment by benjaminguttmann-avtq** [comment]
Hi @andinod ,

not sure what you tried to adjust the code. 
But maybe check [this out](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/CONTRIBUTING.md#submitting-a-pull-request) to get to know how you can submit a PR. If you are still having trouble after you tried this out, I can add it for you.

**Comment by andinod** [comment]
Hi @benjaminguttmann-avtq 

Thanks for the information, I have already submitted the PR.
