### ISSUE TITLE
Grafana dashboard Exists and no Alerts Configured.

### ISSUE THREAD

**Issue by Muruganfly03** [bosh-prometheus/prometheus-boshrelease#326]
Hi Team

 Grafana dashboard contains major Key metrics but not configured with Alerts. Kindly let us know whether any template that contains all alerts configured apart from default template.

**Comment by benjaminguttmann-avtq** [comment]
Hi @Muruganfly03 ,

do you talk about alerts regarding Cloud Foundry? In the BOSH release the alerting is done by the Prometheus/Alertmanager. There are certain alerts prepared you can use. Grafana is just used for visualization. 

Br

**Comment by Muruganfly03** [comment]
Hi Benjamin

                     Yes its related to Cloud Foundry.
There are certain alerts prepared you can use - If we want to know whether we want to add Few KPIs suggested by Pivotal. How we can configure and make it live. 

Pivotal Suggested KPIs.
https://docs.pivotal.io/pivotalcf/2-5/monitoring/kpi.html

I am able to see few of dashboard which exists in Grafana and no Alerts configured(From our existing template).

**Comment by benjaminguttmann-avtq** [comment]
Hi,

the pre-defined alerts from prometheus are located here: https://github.com/bosh-prometheus/prometheus-boshrelease/tree/master/jobs/cloudfoundry_alerts/templates

I think at least some of them are taking care of those KPIs suggested by Pivotal.

**Comment by Muruganfly03** [comment]
Hi Benjamain

The Question is how we can add missing KPIs which is suggested by Pivotal.

How we can Configure those missing KPIs make it live in our environment.

**Comment by benjaminguttmann-avtq** [comment]
Hi,

either you create PR to add this missing KPIs for the release or you add a [property](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/76476e9ecf920094ef52e4fab7cf9a89c8d95236/jobs/prometheus2/spec#L44) in your manifest to add own custom alert rules to prometheus.
