### ISSUE TITLE
Prometheus 23.3 support Xenial Stemcell 

### ISSUE THREAD

**Issue by Muruganfly03** [bosh-prometheus/prometheus-boshrelease#328]
Hi Team,

I am using Prometheus 23.3.0 in our environment which is using stemcell -
bosh-vsphere-esxi-ubuntu-trusty-go_agent/3541.34

Kindly confirm whether Prometheus 23.3.0 version support Xenial stemcell?

**Comment by benjaminguttmann-avtq** [comment]
Hi @Muruganfly03 , 

with `v24.0.0` the bosh release started to use xenial stemcells as default stemcell. Nevertheless we switched to use xenial stemcells (via ops file) before that and did not see any issues so far. 

Hope this helps
