### ISSUE TITLE
No DataPoints for CloudFoundry: AppLantency

### ISSUE THREAD

**Issue by san4ever** [bosh-prometheus/prometheus-boshrelease#332]

**Comment by benjaminguttmann-avtq** [comment]
Hi @san4ever ,

this might be related to the issue discussed here => https://github.com/bosh-prometheus/prometheus-boshrelease/issues/318

**Comment by san4ever** [comment]
![image](https://user-images.githubusercontent.com/29483634/62934204-9d8c0000-bde1-11e9-85bb-82135ea74265.png)

Here is a snippet of our prometheus manifest.yml

**Comment by san4ever** [comment]
Tried the below combination   with cf-xx deployment-name. It also didn't work. Can some one help on this.
logging:
          url: https://log-stream.((system_domain))
          use_legacy_firehose: false

**Comment by benjaminguttmann-avtq** [comment]
@san4ever , did you also ensure that the app you checking for values is actually running and gets visited otherwise you'll see no datapoints as well

**Comment by san4ever** [comment]
Yeah.. even for up and running app it is showing "no data points"
We have upgraded to 25.0.0 in our PROD foundation as well.. in that as well data is not populating up

**Comment by benjaminguttmann-avtq** [comment]
@san4ever could you paste another dashboard screenshot here after you switched to cf-xxx?

**Comment by shanmuksandeep** [comment]
Hi @benjaminguttmann-avtq 
Shared the dashboard screenshot 
![image](https://user-images.githubusercontent.com/13391402/66504043-f75d2d80-eae5-11e9-915d-2163753f61eb.png)

**Comment by benjaminguttmann-avtq** [comment]
Closing. Fixed with #423
