### ISSUE TITLE
Why there are duplicated target for cf_exportor and firehose_exportor?

### ISSUE THREAD

**Issue by MatthewPJ** [bosh-prometheus/prometheus-boshrelease#335]
I am not familied with bosh release job so can you please advised why there are duplicated exportor in my deployment? seems others have same confusion. Take cf_exportor for example, there are two configuration part in prometheus.yml:
one is in file service discovery:
`
{ file_sd_configs: [ { files: [ '/var/vcap/store/bosh_exporter/bosh_target_groups.json' ] } ],
       job_name: 'cf',
       relabel_configs: 
        [ { action: 'keep',
            regex: 'cf_exporter',
            source_labels: [ '__meta_bosh_job_process_name' ] },
          { regex: '(.*)',
            replacement: '${1}:9193',
            source_labels: [ '__address__' ],
            target_label: '__address__' } ],
       scrape_interval: '4m',
       scrape_timeout: '2m' }
`
another likes hardcode:
`{ job_name: 'cf_exporter',
       static_configs: [ { targets: [ 'localhost:9193' ] } ] } `

**Comment by benjaminguttmann-avtq** [comment]
Hi @MatthewPJ 

can you share any information which ops file you are applying when you deploy prometheus ? Like that it makes it easier to check on your question.
