### ISSUE TITLE
No data points from cf-exporter in Prometheus 25.0.0

### ISSUE THREAD

**Issue by san4ever** [bosh-prometheus/prometheus-boshrelease#340]
We have upgraded our PAS from 2.4 to 2.6 . We have update bosh proemetheus from 24.1.0 to 25.0.0 . We are not getting metrics for cloudfoundry latency metrics. 
Could you help us in fixing this. 
Let us know any information needed

**Comment by roberto-yslas** [comment]
I had this problem as well.  I found some documentation that indicated that you need to assign your 
cf-<guid> deployment name as the value for metron_deployment_name in your deployment.
In our case we had to add scrape config for the cf_exporter since our foundation wasn't responding very fast.

      scrape_interval: 2m
      scrape_timeout: 1m

I will say this is very strange because I have several implementations of prometheus and the two I have running on 25 - on one I didn't have to make these changes.  On the other I did.

**Comment by shanmuksandeep** [comment]
Hey @roberto-yslas 
Can you help me where can i get name for **metron_deployment_name**

**Comment by shanmuksandeep** [comment]
Hi @roberto-yslas 
Here is snipped for firehose_exporter and cf_exporter job  . Let us know for any changes i have modify in these jobs
![image](https://user-images.githubusercontent.com/13391402/66492255-b78c4b00-ead1-11e9-853a-1f9c8708c918.png)
![image](https://user-images.githubusercontent.com/13391402/66493028-fec70b80-ead2-11e9-8e46-f972f4809ecf.png)

**Comment by roberto-yslas** [comment]
snip from the monitor-cf.yml operator file:
- type: replace
  path: /instance_groups/name=prometheus2/jobs/-
  value:
    name: cf_exporter
    release: prometheus
    properties:
      cf_exporter:
        cf:
          api_url: https://api.((system_domain))
          client_id: cf_exporter
          client_secret: "((uaa_clients_cf_exporter_secret))"
          deployment_name: ((metron_deployment_name))
        metrics:
          environment: "((metrics_environment))"
        skip_ssl_verify: ((skip_ssl_verify))

for the interpolated variable metron_deployment_name you should put your cf-<guid> of your CF deployment in your foundation.

bosh -e <your-foundation-env> deployments | grep cf 

HTH,
Rob

**Comment by roberto-yslas** [comment]
e.g.

[bldbxops@peplap03496 prometheus25]$ bosh -e dev-director deployments | grep cf
                                                                                                                                    
cf-a66dec9161eca2c38d11                                 backup-and-restore-sdk/1.12.0           bosh-azure-hyperv-ubuntu-xenial-go_agent/250.99         -                                       latest
                                                        cf-autoscaling/219        


**metron_deployment_name=cf-a66dec9161eca2c38d11**

**Comment by san4ever** [comment]
Hi @roberto-yslas 
We even tried to give complete cf deployment name. But data is not populating 
![image](https://user-images.githubusercontent.com/29483634/66941390-6a295400-f064-11e9-8e3e-a83433e95300.png)

**Comment by san4ever** [comment]
Hi @roberto-yslas 
Could you give insights on this. Tried changing metron name with cf deployment didn;t solve the issue yet
Also can you please review this below issue, in case you faced in your foundation
https://github.com/bosh-prometheus/prometheus-boshrelease/issues/359

**Comment by roberto-yslas** [comment]
It is not the deployment_name that you need to modify; that is only a label.
It is the metron_deployment_name that you need to set to your cf deployment.

**Comment by san4ever** [comment]
Hi @roberto-yslas 
Yes Instead of metron_deployment_name --> We gave cf-deployment name. Also have attached the snippet in above comment. 
Could you also suggest other option so that i will tweak into

**Comment by roberto-yslas** [comment]
That's what worked for me - don't know why it's not working for you.

**Comment by san4ever** [comment]
Can you also confirm your PAS and Prometheus version please

**Comment by benjaminguttmann-avtq** [comment]
@san4ever does the issue still persist?

**Comment by benjaminguttmann-avtq** [comment]
Closed due to inactivity; Please feel free to re-open if issue still persists
