### ISSUE TITLE
Selectively enable/disable components installation

### ISSUE THREAD

**Issue by foofoo-2** [bosh-prometheus/prometheus-boshrelease#342]
Hi All,

We would like to use this BOSH release to deploy multiple instances with different configurations. For example, one of them would only run a simple Prometheus instance (without Grafana and Alertmanager), another one would run Prometheus+Alertmanager (without Grafana) and a third one would only run Grafana (without Prometheus and Alertmanager).

Do you see an easy way to do that? I did not find options to selectively enable (or disable) components.

Thanks in advance for your help!

**Comment by frodenas** [comment]
You'll need to create your own manifest files (based on [prometheus.yml](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/manifests/prometheus.yml)), enabling and disabling the components you want for each deployment.
