### ISSUE TITLE
Apps: System dashboard show no data points in Grafana

### ISSUE THREAD

**Issue by mnk628** [bosh-prometheus/prometheus-boshrelease#343]
Hi,

I deployed Prometheus v25.0.0 after deploying new PAS v2.5.8.
Vms in Prometheus works well and Bosh: Jobs dashboard shows full data,
but Apps: System dashboard only shows "No data points" with no metrics.(See the screenshot below)
![20191008_grafana_apps_system](https://user-images.githubusercontent.com/52313616/66372370-c515d800-e9e0-11e9-93ef-2206fd0c19cf.png)

Also, Prometheus has been triggered some alerts, "FirehoseExporterLastMetricReceivedTooOld", "FirehoseExporterLastEnvelopeReceivedTooOld" and "PrometheusScrapeError".
I guess there is some lack the configuration in cf exporter and firehose exporter, 
but could you tell me any advices to solve this issue?

Here's the list of configurations that I already added:

-  logging_url configuration in firehose exporter
-  metron_deployment_name like cf-xxxxxxxx

Thanks.

**Comment by benjaminguttmann-avtq** [comment]
Hi @mnk628 ,

so I guess you already checked the possible solutions in here (https://github.com/bosh-prometheus/prometheus-boshrelease/issues/305)?

Maybe these PR changes can help you to solve your issue? https://github.com/bosh-prometheus/prometheus-boshrelease/pull/285

**Comment by mnk628** [comment]
Hi @benjaminguttmann-avtq ,

Yes, I already set cf-xxxxx as metron_deployment_name in monitor_cf.yml.
I also added logging_url with reference to #318 , but Apps: System dashboard still shows no data.

I don't use CF Isolation Segment, so we don't need to consider monitering Isolation Segment.

Please let me know if there are more settings that should be changed.

**Comment by benjaminguttmann-avtq** [comment]
@mnk628 First thing you need to check if you can see values for the metric `cf_application_info` in Prometheus `/graph` because that metric is used to fill data into the drop downs. Without that value you will not be able to use the dashboard.

**Comment by mnk628** [comment]
Hi @benjaminguttmann-avtq ,

I searched for cf_application_info in the Prometheus /graph pulldown, but I couldn't find the metric.

<img width="960" alt="20191011_prometheus_graph" src="https://user-images.githubusercontent.com/52313616/66617645-ee1caf80-ec10-11e9-813c-b00a3da8c622.png">

**Comment by benjaminguttmann-avtq** [comment]
So I guess that is the issue why the dashboard is not filled at all.. What does the Prometheus>Status>Targets say? 

It seems like the CF Exporter is not working at all

**Comment by mnk628** [comment]
@benjaminguttmann-avtq Yes, I found cf_exporter is down because of connection refused.

<img width="960" alt="20191011_prometheus_target" src="https://user-images.githubusercontent.com/52313616/66631964-5cc63100-ec42-11e9-893c-20d77b3c58e6.png">

**Comment by benjaminguttmann-avtq** [comment]
@mnk628 Were you able to fix the issue?
