### ISSUE TITLE
Certain exporters expose credentials in process table

### ISSUE THREAD

**Issue by aegershman** [bosh-prometheus/prometheus-boshrelease#353]
Some of the exporters (specifically firehose and cf) expose credentials in the process table (`ps aux`); I've redacted the credentials here. We've recently started experimenting with tools like `twistlock` and `nessus`, which when they perform scans tend to dump the current process table, which ends up dumping the passed credentials in plaintext. Whups.

I'm guessing the alternative is probably just having the credentials stored on disk in a config file and having the exporters load from that config.

>root      3786  2.7  0.6 118732 56964 ?        S<l  Nov08 113:30 firehose_exporter --uaa.url=https://uaa.sys.sandbox.example.biz.io --uaa.client-id=firehose_exporter --uaa.client-secret=XYZ-I-REDACTED-THIS_xyz --doppler.subscription-id=sandbox --doppler.max-retry-count=300 --logging.url=wss://doppler.sys.sandbox.example.biz.io:4443 --logging.use-legacy-firehose --metrics.environment=sandbox --web.listen-address=:9186

Is there a way to have these credentials not exposed in the process table? Any thoughts on this?

Thanks for any time & consideration 👍

**Comment by frodenas** [comment]
The easiest solution is to use environment variables. The firehose and cf exporters already support them, instead of sending the value via flag (which will appear at the process table), you can set an environment variable and the exporter will read it instead of the one from the flag.

**Comment by aegershman** [comment]
gotcha: https://github.com/bosh-prometheus/firehose_exporter#flags

so in the case of this bosh-release, would there be interest in a PR which swaps [passing values via flags](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/jobs/firehose_exporter/templates/bin/firehose_exporter_ctl#L39-L40) to exporting env values similar to [how the `HTTP_PROXY` env vars are done?](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/jobs/firehose_exporter/templates/bin/firehose_exporter_ctl#L24-L35)

No worries if a PR wouldn't be considered, though if they're functionally the same, it seems like leveraging env vars instead would be a drop-in replacement?

**Comment by frodenas** [comment]
Sure, a PR will be appreciated!
