### ISSUE TITLE
NO firehose_http_start_stop_client_request_duration_seconds metric

### ISSUE THREAD

**Issue by Alexvianet** [bosh-prometheus/prometheus-boshrelease#363]
I have the latest promehtues bosh release v26.1.0
 firehose_exporter   config include:
   --filter.events="ContainerMetric,CounterEvent,HttpStartStop" \

And now I do not have firehose_http_start_stop_client_request_duration_seconds metrics:
![Screenshot from 2019-12-03 21-35-24](https://user-images.githubusercontent.com/17483589/70083371-eed03180-1614-11ea-8705-cba303ebcf3b.png)

PCF Ops Manager v2.5.21-build.297;

**Comment by rpcarl** [comment]
do sum / count

**Comment by benjaminguttmann-avtq** [comment]
Closing. Fixed with #423
