### ISSUE TITLE
Prometheus Auto Upgrade

### ISSUE THREAD

**Issue by Muruganfly03** [bosh-prometheus/prometheus-boshrelease#365]
Is there any automation in-place to automatically collect new Prometheus bosh-version and upload to our Private registry.  How we can track automatically if any new version released?

It would be helpful for my automation during every releases. Any suggestion and workflow are highly appreciated.

**Comment by benjaminguttmann-avtq** [comment]
@Muruganfly03 not sure which kind of automation you are using, but e.g. with concourse you can watch git repositories and if a new release version is created you can automatically trigger some task 

https://concourse-ci.org
https://github.com/concourse/github-release-resource

**Comment by benjaminguttmann-avtq** [comment]
Closed due to inactivity; Please feel free to re-open if issue still persists.
