### ISSUE TITLE
Create MongoDB dashboards & alerts

### ISSUE THREAD

**Issue by frodenas** [bosh-prometheus/prometheus-boshrelease#37]
The [MongoDB dashboards](https://github.com/cloudfoundry-community/prometheus-boshrelease/tree/master/src/mongodb_dashboards) are currently empty and there is no job/package for MongoDB alerts.

**Comment by Alexvianet** [comment]
any updates can U add https://grafana.com/dashboards/2583

**Comment by Alexvianet** [comment]
noneed if  grafana on postgres db store
