### ISSUE TITLE
error when deploying last prometheus-boshrelease 26.1.0

### ISSUE THREAD

**Issue by jyriok** [bosh-prometheus/prometheus-boshrelease#371]
Hello,

when i try to update prometheus bosh release from 25.0.0 to 26.1.0 , i have this errors 

i have this erros 
```
  instance_groups:
  - name: grafana
    jobs:
    - name: grafana
      properties:
        grafana:
          prometheus:
            dashboard_folders:
            - name: BOSH
              files:
+             - "/var/vcap/jobs/credhub_dashboards/*.json"
+   - name: credhub_dashboards
+     release: prometheus


Continue? [yN]: y

Task 362485

Task 362485 | 10:48:38 | Error: Job 'credhub_dashboards' not found in release 'prometheus'
```

i have done somthing wrong ?  :)

**Comment by Infra-Red** [comment]
Hi @jyriok. Are you using `master` branch? Please switch to `26.1.0` tag and try again.

**Comment by jyriok** [comment]
i use the 26.1.0 tag and on the file "prometheus-26.1.0.yml" i didn't find some info about credhub_dashboards :(

**Comment by jyriok** [comment]
bad move :(  i close accidentaly my issue, can you re-open it please, i don't have right to do that i think

**Comment by jyriok** [comment]
i use it as a submodule :
 0fd52fbbd68a7e8ade5f9825f9774d61ce274202 prometheus-boshrelease/26.1.0 (v26.1.0-30-g0fd52fb)

**Comment by jyriok** [comment]
i didn't see "credhub_dashboards" item on the build section
https://github.com/bosh-prometheus/prometheus-boshrelease/tree/v26.1.0/.final_builds/jobs

i guess the credhub dashboard is not ready to use ?

**Comment by Infra-Red** [comment]
@jyriok `credhub_dashboards` job [was introduced ](https://github.com/bosh-prometheus/prometheus-boshrelease/commit/c1301891bd1497fc70d79884077ed86fe7293300#diff-f1296e2fc05eaba1e55d8d6991c5d327)after v26.1.0 release. You need to use manifest and opsfiles for `v26.1.0` tag. `master` branch is already ahead of `v26.1.0` tag.

**Comment by jyriok** [comment]
thanks for your answer. my mistake is to have chekout master instead the good branch :) (despite have label on submodule :)) 
ok now with the good files, that work and , if i well understand , on the next release , we will obtain a credhub dashboard :) (v26.2.0 ) ?
