### ISSUE TITLE
Rabbimq: Firehose mentrics is not picking the value

### ISSUE THREAD

**Issue by ranjithfd** [bosh-prometheus/prometheus-boshrelease#373]
Please find the below mentioned firehose mentrics is not picking the value in our environment, we need this to be monitored in prometheus. please suggest any methods to get this issue closed. 

firehose_value_metric_p_rabbitmq_num_cpus
firehose_value_metric_p_rabbitmq_memory_stats_num_frees
firehose_value_metric_p_rabbitmq_memory_stats_num_mallocs
firehose_value_metric_p_rabbitmq_memory_stats_last_gc_pause_time_ns
firehose_value_metric_p_rabbitmq_memory_stats_num_bytes_allocated_heap
firehose_value_metric_p_rabbitmq_memory_stats_num_bytes_allocated_stack
firehose_value_metric_p_rabbitmq_memory_stats_num_bytes_allocated
firehose_value_metric_p_rabbitmq_num_go_routines

**Comment by benjaminguttmann-avtq** [comment]
Closed due to inactivity; Please feel free to re-open if issue still persists
