### ISSUE TITLE
Cleanup grafana session properties from prometheus.yml

### ISSUE THREAD

**Issue by forbushbl** [bosh-prometheus/prometheus-boshrelease#376]
It looks like the grafana job was recently updated to remove session properties but this didn't get cleaned up from the manifests (see [manifests/prometheus.yml L100-L105](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/v26.2.0/manifests/prometheus.yml#L100-L105)).

**Comment by frodenas** [comment]
Fixed at #377
