### ISSUE TITLE
Grafana data retention

### ISSUE THREAD

**Issue by Muruganfly03** [bosh-prometheus/prometheus-boshrelease#381]
Hi Team

In grafana we have data only for 15 days. Kindly let me know where we need to update the retention period.

I found the --storage.tsdb.retention.time configuration needs to be updated, but no information where it is available and how to update that one?

Thanks

**Comment by benjaminguttmann-avtq** [comment]
Hi @Muruganfly03 ,

this is the spec you need to adjust  => https://github.com/bosh-prometheus/prometheus-boshrelease/blob/5dd3646a42a201c44bcc2f18486dea33f48c8856/jobs/prometheus2/spec#L79

Hope this helps

**Comment by benjaminguttmann-avtq** [comment]
@Muruganfly03 did that help to improve the situation for you ?
