### ISSUE TITLE
Authenticate to UAA using NGINX

### ISSUE THREAD

**Issue by giva01121** [bosh-prometheus/prometheus-boshrelease#383]
Hi, 
is there a way to configure the integrated NGINX to use UAA, or I need to install one in front of the prometheus ?

**Comment by benjaminguttmann-avtq** [comment]
Hi @giva01121 isn't that question not already answered in your other question? #217

**Comment by giva01121** [comment]
I'm more asking if we can user NGINX in order to access prometheus on port 9090 for example

**Comment by benjaminguttmann-avtq** [comment]
The default deployment includes a nginx that can be used to access prometheus/grafana/alertmanager

**Comment by benjaminguttmann-avtq** [comment]
Closed due to inactivity; Please feel free to re-open if issue still persists
