### ISSUE TITLE
Apps:LATENCY Panel data missing after upgrade to 26.2.0

### ISSUE THREAD

**Issue by Muruganfly03** [bosh-prometheus/prometheus-boshrelease#384]
One of the panel updated, rest two missing to update graph. Whay may be the reason for this sone. Not able to see any logs on Firehose exporter and cf_exporter. Attached the screenshot for reference.
![Capture_Apps](https://user-images.githubusercontent.com/46529014/78553763-71693780-7827-11ea-8f20-6bab1add1dbb.JPG)

**Comment by vChrisR** [comment]
I noted that the two graphs with "No data" ware using a non-existent metric. They are using "firehose_http_start_stop_client_request_duration_seconds" and "firehose_http_start_stop_server_request_duration_seconds" Which don't exist. There is a firehose_http_start_stop_(client/server)_request_duration_seconds_sum and _count though. Not sure which one to use.

**Comment by benjaminguttmann-avtq** [comment]
Closing. Fixed with #423

**Comment by benjaminguttmann-avtq** [comment]
Closing. Fixed with #423
