### ISSUE TITLE
Update cf queries

### ISSUE THREAD

**Issue by theautoroboto** [bosh-prometheus/prometheus-boshrelease#389]
Since upgrading, I see the queries for the cf dashboards are no longer reporting stats.  This looks like a fairly simple change.

`"bosh_deployment=~"$bosh_deployment" needs to be bosh_deployment=~"$bosh_deployment.*"`

For example
`
avg(firehose_http_start_stop_client_request_duration_seconds_sum{environment=~"$environment",bosh_deployment=~"$bosh_deployment",application_id=~"$cf_application_id"} / firehose_http_start_stop_client_request_duration_seconds_count{environment=~"$environment",bosh_deployment=~"$bosh_deployment",application_id=~"$cf_application_id"})
`
should be 
`
avg(firehose_http_start_stop_client_request_duration_seconds_sum{environment=~"$environment",bosh_deployment=~"$bosh_deployment.*",application_id=~"$cf_application_id"} / firehose_http_start_stop_client_request_duration_seconds_count{environment=~"$environment",bosh_deployment=~"$bosh_deployment.*",application_id=~"$cf_application_id"})
`

**Comment by benjaminguttmann-avtq** [comment]
@theautoroboto 
Do you want to prepare a PR to address those changes?

**Comment by theautoroboto** [comment]
Yes, I would be happy to do that.

**Comment by benjaminguttmann-avtq** [comment]
Closing. Fixed with #423

**Comment by benjaminguttmann-avtq** [comment]
Closing. Fixed with #423
