### ISSUE TITLE
Evaluate bumping to alertmanager v0.21.0

### ISSUE THREAD

**Issue by aegershman** [bosh-prometheus/prometheus-boshrelease#398]
Placeholder to evaluate bumping to the latest alertmanager, v0.21.0: https://github.com/prometheus/alertmanager/releases/tag/v0.21.0

**Comment by frodenas** [comment]
Included in [v26.3.0](https://github.com/bosh-prometheus/prometheus-boshrelease/releases/tag/v26.3.0)
