### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by amuessig** [bosh-prometheus/prometheus-boshrelease#400]
Hi,

just wondering if this repo is still actively maintained? 
If possible, I would like to see some version bumps, i.e., grafana >= v6.7
There are even some open pull requests for this, i.e., #392 and #394 

What do you think?

**Comment by frodenas** [comment]
I just cut a new release [v26.3.0](https://github.com/bosh-prometheus/prometheus-boshrelease/releases/tag/v26.3.0)
