### ISSUE TITLE
Evaluate grafana 7.1.5 + prometheus 2.21.0

### ISSUE THREAD

**Issue by aegershman** [bosh-prometheus/prometheus-boshrelease#404]
Apologies if spammy, just putting down a placeholder for evaluating to check for any property/functionality differences and bumps for...

- grafana 7.1.5 (https://github.com/grafana/grafana/releases/tag/v7.1.5)
- prometheus 2.21.0 (https://github.com/prometheus/prometheus/releases/tag/v2.21.0)

👍 thanks for the time, sorry this isn't in the form of a PR, just putting this here as potential backlog eval

**Comment by frodenas** [comment]
Included in [v26.3.0](https://github.com/bosh-prometheus/prometheus-boshrelease/releases/tag/v26.3.0)
