### ISSUE TITLE
Redis dashboard not listing data

### ISSUE THREAD

**Issue by Murugan2all** [bosh-prometheus/prometheus-boshrelease#405]
Hi Team

            Recently we upgraded the Prometheus from 23.3.0 to 26.2.0. We are able to see all grafana dashboard updates, except Redis. Kindly let me know anything we need to update to fix this issue. Attached the screenshot for reference, not reflecting data's.

![image](https://user-images.githubusercontent.com/15375609/94422479-c9647380-01a4-11eb-8e63-dc9382518210.png)

Able to view data for other data service Rabbitmq. Kindly let me know any additional information required.

**Comment by benjaminguttmann-avtq** [comment]
Closed due to inactivity; Please feel free to re-open if issue still persists
