### ISSUE TITLE
Monitoring Bosh Director itself?

### ISSUE THREAD

**Issue by stwomack** [bosh-prometheus/prometheus-boshrelease#410]
We use this bosh release for prometheus today, and we are not getting any VM metrics for the bosh director itself. Was curious if there was a prometheus scrape target or something that could be used to get the health stats of the *director itself*. Also, alarms would be nice. /cc @xyloman

**Comment by gorkemozlu** [comment]
same here.

**Comment by benjaminguttmann-avtq** [comment]
As far as I know there is specific endpoint nor exporter that allows you to gather metrics from a bosh director that was created with create-env and not deployed by another director. You can get some basic bosh related information by enabling the following metrics endpoint => https://github.com/cloudfoundry/bosh-deployment/blob/master/experimental/enable-metrics.yml

**Comment by xyloman** [comment]
@benjaminguttmann-avtq do you know if an operator exists in this bosh release to fetch the metrics predefined alerts, and dashboards similar to the other components?

**Comment by benjaminguttmann-avtq** [comment]
@xyloman no not yet, if there is any interest in that I could add an ops file to enable something like that based on the approach we are currently using.

**Comment by benjaminguttmann-avtq** [comment]
Kind of duplicate to #399
