### ISSUE TITLE
bionic stemcell. grafana startup freeze

### ISSUE THREAD

**Issue by poblin-orange** [bosh-prometheus/prometheus-boshrelease#416]
Testing
- prometheus bosh release 26.4.0
- bionic stemcell 0.19

We observe grafana start freeze (post-start)

**Comment by benjaminguttmann-avtq** [comment]
Hi there, 

seeing same issues with bionic stemcell 0.24

**Comment by poblin-orange** [comment]
Seems the nc command checking the open grafana port is the culprit:
```
broker/801ac959-c4b5-4251-a4be-fd823f32355e:/var/vcap/sys/log/grafana# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root      5880   704  0 Apr19 ?        00:00:00 bash /var/vcap/jobs/grafana/bin/post-start
root      5887  5880  0 Apr19 ?        00:00:00 bash /var/vcap/jobs/grafana/bin/grafana-admin-password
root      5891  5887  0 Apr19 ?        00:00:00 nc 127.0.0.1 3000
```

```
broker/801ac959-c4b5-4251-a4be-fd823f32355e:/var/vcap/sys/log/grafana# nc -vz 127.0.0.1 3000
Connection to 127.0.0.1 3000 port [tcp/*] succeeded!

broker/801ac959-c4b5-4251-a4be-fd823f32355e:/var/vcap/sys/log/grafana# nc  127.0.0.1 3000
=> freeze
```

**Comment by benjaminguttmann-avtq** [comment]
Yes, that is was I also just found out... currently trying to figure out why this is happening because a curl on http://localhost:3000 is working fine

**Comment by benjaminguttmann-avtq** [comment]
So it seems like

`nc 127.0.0.1 3000 < /dev/null`

is behaving differently on Xenial and Bionic. For Xenial it immediately returns, for Bionic it does not. This approach was apparently applied to fix issues with [cent os](https://github.com/bosh-prometheus/prometheus-boshrelease/commit/24d091599aa0784dcef6b0a73eedd4afaa00f156).

**Comment by benjaminguttmann-avtq** [comment]
We could adjust the following line

https://github.com/bosh-prometheus/prometheus-boshrelease/blob/9cccf9494a86b0b2420b5d9dd086397cbecf7c72/jobs/grafana/templates/bin/grafana-admin-password#L8

to look like the following 

` if nc -w 5 127.0.0.1 <%= p('grafana.server.http_port') %> < /dev/null; then`
