### ISSUE TITLE
Update grafana to 7.5.15

### ISSUE THREAD

**Issue by bengerman13** [bosh-prometheus/prometheus-boshrelease#435]
grafana 7.5.15 has some fixes we'd like to pull in. I've checked the [changelog](https://github.com/grafana/grafana/blob/main/CHANGELOG.md?plain=1#L1318-L1335) and there's nothing major, just minor fixes.

Happy to help if there's anything other than uploading blobs required :)

**Comment by benjaminguttmann-avtq** [comment]
Hi @bengerman13 ,

version v27.0.0 should fix your issue.
