### ISSUE TITLE
Any plans for upgrading 7.5.17? We are having issues with Chrome browsers

### ISSUE THREAD

**Issue by JakubKC** [bosh-prometheus/prometheus-boshrelease#447]
There was a serious bug fix released in the 7.15.17 solving issues with editing input fields in Chrome and Chrome-like browsers. 
Could you, please, make a release with this version?

Links:
https://github.com/grafana/grafana/pull/54566
https://grafana.com/grafana/download/7.5.17

**Comment by mator** [comment]
We could benefit from 7.5.x fix as well. Thanks!

**Comment by benjaminguttmann-avtq** [comment]
Hi @JakubKC and @mator 

we just released [27.2.0](https://github.com/bosh-prometheus/prometheus-boshrelease/releases/tag/v27.2.0) which includes the latest Grafana 7 version.

Thanks for opening the issue. 

BR,
Benjamin
