### ISSUE TITLE
Grafana cannot deploy with custom home dashboard

### ISSUE THREAD

**Issue by psycofdj** [bosh-prometheus/prometheus-boshrelease#449]
Since version [`v27.2.0`](https://github.com/bosh-prometheus/prometheus-boshrelease/releases/tag/v27.2.1) and its upgrade to grafana [`8.5.15`](https://github.com/grafana/grafana/releases/tag/v8.5.15), the post-start script fail for grafana

```
Task 369950 | 10:17:55 | L executing post-start: grafana/ff8ec6a4-ac9b-4222-9875-2a552b0d6b74 (0) (canary) (00:00:40)
                       L Error: Action Failed get_task: Task 3006e3aa-76f5-4619-76d4-24572f123766 result: 1 of 2 post-start scripts failed. Failed Jobs: grafana. Successful Jobs: bosh-dns.
Task 369950 | 10:18:01 | Error: Action Failed get_task: Task 3006e3aa-76f5-4619-76d4-24572f123766 result: 1 of 2 post-start scripts failed. Failed Jobs: grafana. Successful Jobs: bosh-dns.
```

After some investigation, the error occurs in the script `/var/vcap/jobs/grafana/bin/grafana-homepage` which use grafana API to:
1. uploads a custom home dashboard given in the `grafana.dashboards.custom_homepage_json` property
2. sets preferences to use this dashboard as home dashboad

Those api calls are made using the [`slugs`](https://grafana.com/docs/grafana/v7.5/http_api/dashboard/#get-dashboard-by-slug) endpoints which were deprecated in `v7` and removed in `v8`.

**Comment by benjaminguttmann-avtq** [comment]
So if I get it right this happens only if you have the `grafana.dashboards.custom_homepage_json` configured, right?

**Comment by psycofdj** [comment]
indeed
