### ISSUE TITLE
bosh_exporter 3.6.0 compilation failing due to naming change

### ISSUE THREAD

**Issue by lodener** [bosh-prometheus/prometheus-boshrelease#481]
Pre-3.5.0 assets were named following a `bosh_exporter-version` scheme, with 3.5.0 this seems to have changed to `bosh_exporter_version` (_ instead of -). With the bosh_exporter bump to 3.6.0 in the latest prometheus-boshrelease, compilation seems to be failing due to this change:

> Error: Action Failed get_task: Task *** result: Compiling package bosh_exporter: Running packaging script: Running packaging script: Command exited with 1; Stdout: bosh_exporter_3.6.0.linux-amd64/NOTICE
> bosh_exporter_3.6.0.linux-amd64/README.md
> bosh_exporter_3.6.0.linux-amd64/bosh_exporter
> , Stderr: + mkdir -p /var/vcap/packages/bosh_exporter/common
> + cp -a /var/vcap/data/compile/bosh_exporter/common/utils.sh /var/vcap/packages/bosh_exporter/common
> + mkdir -p /var/vcap/packages/bosh_exporter/bin
> + tar xzvf /var/vcap/data/compile/bosh_exporter/bosh_exporter/bosh_exporter-3.6.0.linux-amd64.tar.gz
> + cp -a '/var/vcap/data/compile/bosh_exporter/bosh_exporter-3.6.0.linux-amd64/*' /var/vcap/packages/bosh_exporter/bin
> cp: cannot stat '/var/vcap/data/compile/bosh_exporter/bosh_exporter-3.6.0.linux-amd64/*': No such file or directory

**Comment by benjaminguttmann-avtq** [comment]
Hi @lodener ,

yes you are right. Thank you for pointing that out. 
I expect there to be a new version of prometheus-boshrelease today, which will also include a fix for this issue.

**Comment by benjaminguttmann-avtq** [comment]
Hi @lodener ,

version v29.4.0 should fix this issue.

**Comment by lodener** [comment]
Looks good, thanks for the quick response/fix @benjaminguttmann-avtq!
