### ISSUE TITLE
Unable to disable retro compatibily on firehose exporter

### ISSUE THREAD

**Issue by mchabane** [bosh-prometheus/prometheus-boshrelease#483]
Hello,

We are trying to disable the retro compatibily on the firehose exporter throught the retro_compat.disable as describe here https://github.com/bosh-prometheus/firehose_exporter, but it seems to not be possible in the bosh release as we see here https://bosh.io/jobs/firehose_exporter?source=github.com/cloudfoundry-community/prometheus-boshrelease&version=29.5.0.
There is no retro compat property.

**Comment by mchabane** [comment]
Hi @benjaminguttmann-avtq,

Thanks for your quick answer !

In our case we want the new metrics, for example metrics.namespace_memory_quota instead of metrics.namespace_container_metric_memory_bytes_quota .

As describe here https://github.com/bosh-prometheus/firehose_exporter/blob/master/FAQ.md : Use retro_compat.disable command flag to deactivate retro-compat mode and use new names.

So if i understand, we have to set the flag to true to have the new names.

For the moment, it's set as default (so false) and we have old metrics names.

**Comment by benjaminguttmann-avtq** [comment]
Hi @mchabane ,

you are totally right. Misunderstand it myself.
Are you interested in creating a PR to make the property available for configuration?

**Comment by mchabane** [comment]
I'm not able to test it right now but i think we have to add this:
```
  firehose_exporter.retro_compat.disable:
    description: "Disable retro compatibility"
    default: false
```
  in /jobs/firehose_exporter/spec

and this : 
`  "FIREHOSE_EXPORTER_RETRO_COMPAT_DISABLE"     =>p('firehose_exporter.retro_compat.disable'),`
in jobs/firehose_exporter/templates/bpm.yml.erb

**Comment by mchabane** [comment]
Hi @benjaminguttmann-avtq,

Tank you for the PR !

When the new release should be released?

**Comment by benjaminguttmann-avtq** [comment]
Hi @mchabane 

I hoped to get a CVE fix for Prometheus into the next release, but so far it is only available in RC.
Will work on bumping the last releases tomorrow and create a new release.

**Comment by benjaminguttmann-avtq** [comment]
Hi @mchabane the latest release v29.6.0 includes your PR

**Comment by mchabane** [comment]
Hello,
Thank you, the issue is now resolved :).
