### ISSUE TITLE
wrongly renamed label applicationID

### ISSUE THREAD

**Issue by mchabane** [bosh-prometheus/prometheus-boshrelease#485]
https://github.com/bosh-prometheus/cf_exporter/pull/104

Hello,

Can someone bump the cf exporter version to fix to wrong label applicationID.

Thank you :).

**Comment by benjaminguttmann-avtq** [comment]
Hi @mchabane that issue should be fixed with the latest release v29.6.0

**Comment by mchabane** [comment]
Hello,
Thank you, the issue is now resolved :).
