### ISSUE TITLE
Errands / delete deployment as unhealthy job

### ISSUE THREAD

**Issue by shinji62** [bosh-prometheus/prometheus-boshrelease#6]
Hi,
it's seems that errand / or deleted job/release are count as unhealthy and so trigger alert.
This unhealthy job remain forever right now.

Thanks

**Comment by frodenas** [comment]
It remains for about 5 mins. This is due to https://github.com/prometheus/prometheus/issues/398. I need to figure out how to deal with this at the Alerts & Grafana dashboards.

**Comment by xanderrman** [comment]
@shinji62 just wanted to see if this was still happening; thank you
